/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data about the components comprising an address.
 * @export
 * @interface AddressDataNullable
 */
export interface AddressDataNullable {
    /**
     * The full city name
     * @type {string}
     * @memberof AddressDataNullable
     */
    city: string | null;
    /**
     * The region or state. In API versions 2018-05-22 and earlier, this field is called `state`.
     * Example: `"NC"`
     * @type {string}
     * @memberof AddressDataNullable
     */
    region: string | null;
    /**
     * The full street address
     * Example: `"564 Main Street, APT 15"`
     * @type {string}
     * @memberof AddressDataNullable
     */
    street: string;
    /**
     * The postal code. In API versions 2018-05-22 and earlier, this field is called `zip`.
     * @type {string}
     * @memberof AddressDataNullable
     */
    postal_code: string | null;
    /**
     * The ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof AddressDataNullable
     */
    country: string | null;
}

/**
 * Check if a given object implements the AddressDataNullable interface.
 */
export function instanceOfAddressDataNullable(value: object): boolean {
    if (!('city' in value)) return false;
    if (!('region' in value)) return false;
    if (!('street' in value)) return false;
    if (!('postal_code' in value)) return false;
    if (!('country' in value)) return false;
    return true;
}

export function AddressDataNullableFromJSON(json: any): AddressDataNullable {
    return AddressDataNullableFromJSONTyped(json, false);
}

export function AddressDataNullableFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDataNullable {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'region': json['region'],
        'street': json['street'],
        'postal_code': json['postal_code'],
        'country': json['country'],
    };
}

export function AddressDataNullableToJSON(value?: AddressDataNullable | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'city': value['city'],
        'region': value['region'],
        'street': value['street'],
        'postal_code': value['postal_code'],
        'country': value['country'],
    };
}

