/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
 * @export
 * @interface AssetOwner
 */
export interface AssetOwner {
    [key: string]: any | any;
    /**
     * Account Owner Full Name.
     * @type {string}
     * @memberof AssetOwner
     */
    AssetOwnerText: string | null;
}

/**
 * Check if a given object implements the AssetOwner interface.
 */
export function instanceOfAssetOwner(value: object): boolean {
    if (!('AssetOwnerText' in value)) return false;
    return true;
}

export function AssetOwnerFromJSON(json: any): AssetOwner {
    return AssetOwnerFromJSONTyped(json, false);
}

export function AssetOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetOwner {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'AssetOwnerText': json['AssetOwnerText'],
    };
}

export function AssetOwnerToJSON(value?: AssetOwner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'AssetOwnerText': value['AssetOwnerText'],
    };
}

