/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Loans } from './Loans';
import {
    LoansFromJSON,
    LoansFromJSONTyped,
    LoansToJSON,
} from './Loans';
import type { Parties } from './Parties';
import {
    PartiesFromJSON,
    PartiesFromJSONTyped,
    PartiesToJSON,
} from './Parties';
import type { Services } from './Services';
import {
    ServicesFromJSON,
    ServicesFromJSONTyped,
    ServicesToJSON,
} from './Services';

/**
 * An object representing an Asset Report with Freddie Mac schema.
 * @export
 * @interface AssetReportFreddie
 */
export interface AssetReportFreddie {
    [key: string]: any | any;
    /**
     * 
     * @type {Loans}
     * @memberof AssetReportFreddie
     */
    LOANS: Loans;
    /**
     * 
     * @type {Parties}
     * @memberof AssetReportFreddie
     */
    PARTIES: Parties;
    /**
     * 
     * @type {Services}
     * @memberof AssetReportFreddie
     */
    SERVICES: Services;
}

/**
 * Check if a given object implements the AssetReportFreddie interface.
 */
export function instanceOfAssetReportFreddie(value: object): boolean {
    if (!('LOANS' in value)) return false;
    if (!('PARTIES' in value)) return false;
    if (!('SERVICES' in value)) return false;
    return true;
}

export function AssetReportFreddieFromJSON(json: any): AssetReportFreddie {
    return AssetReportFreddieFromJSONTyped(json, false);
}

export function AssetReportFreddieFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetReportFreddie {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'LOANS': LoansFromJSON(json['LOANS']),
        'PARTIES': PartiesFromJSON(json['PARTIES']),
        'SERVICES': ServicesFromJSON(json['SERVICES']),
    };
}

export function AssetReportFreddieToJSON(value?: AssetReportFreddie | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'LOANS': LoansToJSON(value['LOANS']),
        'PARTIES': PartiesToJSON(value['PARTIES']),
        'SERVICES': ServicesToJSON(value['SERVICES']),
    };
}

