/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the response schema for `/bank_transfer/migrate_account`
 * @export
 * @interface BankTransferMigrateAccountResponse
 */
export interface BankTransferMigrateAccountResponse {
    [key: string]: any | any;
    /**
     * The Plaid `access_token` for the newly created Item.
     * @type {string}
     * @memberof BankTransferMigrateAccountResponse
     */
    access_token: string;
    /**
     * The Plaid `account_id` for the newly created Item.
     * @type {string}
     * @memberof BankTransferMigrateAccountResponse
     */
    account_id: string;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof BankTransferMigrateAccountResponse
     */
    request_id: string;
}

/**
 * Check if a given object implements the BankTransferMigrateAccountResponse interface.
 */
export function instanceOfBankTransferMigrateAccountResponse(value: object): boolean {
    if (!('access_token' in value)) return false;
    if (!('account_id' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function BankTransferMigrateAccountResponseFromJSON(json: any): BankTransferMigrateAccountResponse {
    return BankTransferMigrateAccountResponseFromJSONTyped(json, false);
}

export function BankTransferMigrateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransferMigrateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'access_token': json['access_token'],
        'account_id': json['account_id'],
        'request_id': json['request_id'],
    };
}

export function BankTransferMigrateAccountResponseToJSON(value?: BankTransferMigrateAccountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'access_token': value['access_token'],
        'account_id': value['account_id'],
        'request_id': value['request_id'],
    };
}

