/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEnvironmentValues } from './WebhookEnvironmentValues';
import {
    WebhookEnvironmentValuesFromJSON,
    WebhookEnvironmentValuesFromJSONTyped,
    WebhookEnvironmentValuesToJSON,
} from './WebhookEnvironmentValues';

/**
 * Fired when the Base Report has been generated and `/cra/base_report/get` is ready to be called.  If you attempt to retrieve a Base Report before this webhook has fired, you’ll receive a response with the HTTP status code 400 and a Plaid error code of `PRODUCT_NOT_READY`.
 * @export
 * @interface BaseReportsProductReadyWebhook
 */
export interface BaseReportsProductReadyWebhook {
    [key: string]: any | any;
    /**
     * `BASE_REPORT`
     * @type {string}
     * @memberof BaseReportsProductReadyWebhook
     */
    webhook_type: string;
    /**
     * `PRODUCT_READY`
     * @type {string}
     * @memberof BaseReportsProductReadyWebhook
     */
    webhook_code: string;
    /**
     * The `user_id` corresponding to the User ID the webhook has fired for.
     * @type {string}
     * @memberof BaseReportsProductReadyWebhook
     */
    user_id: string;
    /**
     * 
     * @type {WebhookEnvironmentValues}
     * @memberof BaseReportsProductReadyWebhook
     */
    environment: WebhookEnvironmentValues;
}

/**
 * Check if a given object implements the BaseReportsProductReadyWebhook interface.
 */
export function instanceOfBaseReportsProductReadyWebhook(value: object): boolean {
    if (!('webhook_type' in value)) return false;
    if (!('webhook_code' in value)) return false;
    if (!('user_id' in value)) return false;
    if (!('environment' in value)) return false;
    return true;
}

export function BaseReportsProductReadyWebhookFromJSON(json: any): BaseReportsProductReadyWebhook {
    return BaseReportsProductReadyWebhookFromJSONTyped(json, false);
}

export function BaseReportsProductReadyWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseReportsProductReadyWebhook {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'webhook_type': json['webhook_type'],
        'webhook_code': json['webhook_code'],
        'user_id': json['user_id'],
        'environment': WebhookEnvironmentValuesFromJSON(json['environment']),
    };
}

export function BaseReportsProductReadyWebhookToJSON(value?: BaseReportsProductReadyWebhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'webhook_type': value['webhook_type'],
        'webhook_code': value['webhook_code'],
        'user_id': value['user_id'],
        'environment': WebhookEnvironmentValuesToJSON(value['environment']),
    };
}

