/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BeaconMatchSummaryCode } from './BeaconMatchSummaryCode';
import {
    BeaconMatchSummaryCodeFromJSON,
    BeaconMatchSummaryCodeFromJSONTyped,
    BeaconMatchSummaryCodeToJSON,
} from './BeaconMatchSummaryCode';

/**
 * Analysis of which fields matched between one Beacon User and another.
 * @export
 * @interface BeaconMatchSummaryAnalysis
 */
export interface BeaconMatchSummaryAnalysis {
    [key: string]: any | any;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    address: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    date_of_birth: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    email_address: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    name: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    id_number: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    ip_address: BeaconMatchSummaryCode;
    /**
     * 
     * @type {BeaconMatchSummaryCode}
     * @memberof BeaconMatchSummaryAnalysis
     */
    phone_number: BeaconMatchSummaryCode;
}

/**
 * Check if a given object implements the BeaconMatchSummaryAnalysis interface.
 */
export function instanceOfBeaconMatchSummaryAnalysis(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('date_of_birth' in value)) return false;
    if (!('email_address' in value)) return false;
    if (!('name' in value)) return false;
    if (!('id_number' in value)) return false;
    if (!('ip_address' in value)) return false;
    if (!('phone_number' in value)) return false;
    return true;
}

export function BeaconMatchSummaryAnalysisFromJSON(json: any): BeaconMatchSummaryAnalysis {
    return BeaconMatchSummaryAnalysisFromJSONTyped(json, false);
}

export function BeaconMatchSummaryAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeaconMatchSummaryAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'address': BeaconMatchSummaryCodeFromJSON(json['address']),
        'date_of_birth': BeaconMatchSummaryCodeFromJSON(json['date_of_birth']),
        'email_address': BeaconMatchSummaryCodeFromJSON(json['email_address']),
        'name': BeaconMatchSummaryCodeFromJSON(json['name']),
        'id_number': BeaconMatchSummaryCodeFromJSON(json['id_number']),
        'ip_address': BeaconMatchSummaryCodeFromJSON(json['ip_address']),
        'phone_number': BeaconMatchSummaryCodeFromJSON(json['phone_number']),
    };
}

export function BeaconMatchSummaryAnalysisToJSON(value?: BeaconMatchSummaryAnalysis | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'address': BeaconMatchSummaryCodeToJSON(value['address']),
        'date_of_birth': BeaconMatchSummaryCodeToJSON(value['date_of_birth']),
        'email_address': BeaconMatchSummaryCodeToJSON(value['email_address']),
        'name': BeaconMatchSummaryCodeToJSON(value['name']),
        'id_number': BeaconMatchSummaryCodeToJSON(value['id_number']),
        'ip_address': BeaconMatchSummaryCodeToJSON(value['ip_address']),
        'phone_number': BeaconMatchSummaryCodeToJSON(value['phone_number']),
    };
}

