/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BeaconUserAddress } from './BeaconUserAddress';
import {
    BeaconUserAddressFromJSON,
    BeaconUserAddressFromJSONTyped,
    BeaconUserAddressToJSON,
} from './BeaconUserAddress';
import type { BeaconUserIDNumber } from './BeaconUserIDNumber';
import {
    BeaconUserIDNumberFromJSON,
    BeaconUserIDNumberFromJSONTyped,
    BeaconUserIDNumberToJSON,
} from './BeaconUserIDNumber';
import type { BeaconUserName } from './BeaconUserName';
import {
    BeaconUserNameFromJSON,
    BeaconUserNameFromJSONTyped,
    BeaconUserNameToJSON,
} from './BeaconUserName';

/**
 * A Beacon User's data and resulting analysis when checked against duplicate records and the Beacon Fraud Network.
 * @export
 * @interface BeaconUserData
 */
export interface BeaconUserData {
    [key: string]: any | any;
    /**
     * A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).
     * @type {Date}
     * @memberof BeaconUserData
     */
    date_of_birth: Date;
    /**
     * 
     * @type {BeaconUserName}
     * @memberof BeaconUserData
     */
    name: BeaconUserName;
    /**
     * 
     * @type {BeaconUserAddress}
     * @memberof BeaconUserData
     */
    address: BeaconUserAddress;
    /**
     * A valid email address.
     * @type {string}
     * @memberof BeaconUserData
     */
    email_address: string | null;
    /**
     * A phone number in E.164 format.
     * @type {string}
     * @memberof BeaconUserData
     */
    phone_number: string | null;
    /**
     * 
     * @type {BeaconUserIDNumber}
     * @memberof BeaconUserData
     */
    id_number: BeaconUserIDNumber | null;
    /**
     * An IPv4 or IPV6 address.
     * @type {string}
     * @memberof BeaconUserData
     */
    ip_address: string | null;
}

/**
 * Check if a given object implements the BeaconUserData interface.
 */
export function instanceOfBeaconUserData(value: object): boolean {
    if (!('date_of_birth' in value)) return false;
    if (!('name' in value)) return false;
    if (!('address' in value)) return false;
    if (!('email_address' in value)) return false;
    if (!('phone_number' in value)) return false;
    if (!('id_number' in value)) return false;
    if (!('ip_address' in value)) return false;
    return true;
}

export function BeaconUserDataFromJSON(json: any): BeaconUserData {
    return BeaconUserDataFromJSONTyped(json, false);
}

export function BeaconUserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeaconUserData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'date_of_birth': (new Date(json['date_of_birth'])),
        'name': BeaconUserNameFromJSON(json['name']),
        'address': BeaconUserAddressFromJSON(json['address']),
        'email_address': json['email_address'],
        'phone_number': json['phone_number'],
        'id_number': BeaconUserIDNumberFromJSON(json['id_number']),
        'ip_address': json['ip_address'],
    };
}

export function BeaconUserDataToJSON(value?: BeaconUserData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'date_of_birth': ((value['date_of_birth']).toISOString().substring(0,10)),
        'name': BeaconUserNameToJSON(value['name']),
        'address': BeaconUserAddressToJSON(value['address']),
        'email_address': value['email_address'],
        'phone_number': value['phone_number'],
        'id_number': BeaconUserIDNumberToJSON(value['id_number']),
        'ip_address': value['ip_address'],
    };
}

