/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enum indicating the match type between two Beacon Users.
 * 
 * 
 * `match` indicates that the provided input data was a strong match against the other Beacon User.
 * 
 * `partial_match` indicates the data approximately matched the other Beacon User. For example, "Knope" vs. "Knope-Wyatt" for last name.
 * 
 * `no_match` indicates that Plaid was able to compare this field against the other Beacon User and it did not match the provided input data.
 * 
 * `no_data` indicates that Plaid was unable to compare this field against the original Beacon User because the field was not present in one of the Beacon Users.
 * @export
 */
export const BeaconMatchSummaryCode = {
    Match: 'match',
    PartialMatch: 'partial_match',
    NoMatch: 'no_match',
    NoData: 'no_data'
} as const;
export type BeaconMatchSummaryCode = typeof BeaconMatchSummaryCode[keyof typeof BeaconMatchSummaryCode];


export function BeaconMatchSummaryCodeFromJSON(json: any): BeaconMatchSummaryCode {
    return BeaconMatchSummaryCodeFromJSONTyped(json, false);
}

export function BeaconMatchSummaryCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeaconMatchSummaryCode {
    return json as BeaconMatchSummaryCode;
}

export function BeaconMatchSummaryCodeToJSON(value?: BeaconMatchSummaryCode | null): any {
    return value as any;
}

