/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request input for listing the history of a Beacon User
 * @export
 * @interface BeaconUserHistoryListRequest
 */
export interface BeaconUserHistoryListRequest {
    /**
     * ID of the associated Beacon User.
     * @type {string}
     * @memberof BeaconUserHistoryListRequest
     */
    beacon_user_id: string;
    /**
     * An identifier that determines which page of results you receive.
     * @type {string}
     * @memberof BeaconUserHistoryListRequest
     */
    cursor?: string;
    /**
     * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
     * @type {string}
     * @memberof BeaconUserHistoryListRequest
     */
    client_id?: string;
    /**
     * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
     * @type {string}
     * @memberof BeaconUserHistoryListRequest
     */
    secret?: string;
}

/**
 * Check if a given object implements the BeaconUserHistoryListRequest interface.
 */
export function instanceOfBeaconUserHistoryListRequest(value: object): boolean {
    if (!('beacon_user_id' in value)) return false;
    return true;
}

export function BeaconUserHistoryListRequestFromJSON(json: any): BeaconUserHistoryListRequest {
    return BeaconUserHistoryListRequestFromJSONTyped(json, false);
}

export function BeaconUserHistoryListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeaconUserHistoryListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'beacon_user_id': json['beacon_user_id'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
    };
}

export function BeaconUserHistoryListRequestToJSON(value?: BeaconUserHistoryListRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'beacon_user_id': value['beacon_user_id'],
        'cursor': value['cursor'],
        'client_id': value['client_id'],
        'secret': value['secret'],
    };
}

