/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ISO-3166-1 alpha-2 country code standard.
 * @export
 */
export const CountryCode = {
    Us: 'US',
    Gb: 'GB',
    Es: 'ES',
    Nl: 'NL',
    Fr: 'FR',
    Ie: 'IE',
    Ca: 'CA',
    De: 'DE',
    It: 'IT',
    Pl: 'PL',
    Dk: 'DK',
    No: 'NO',
    Se: 'SE',
    Ee: 'EE',
    Lt: 'LT',
    Lv: 'LV',
    Pt: 'PT',
    Be: 'BE'
} as const;
export type CountryCode = typeof CountryCode[keyof typeof CountryCode];


export function CountryCodeFromJSON(json: any): CountryCode {
    return CountryCodeFromJSONTyped(json, false);
}

export function CountryCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryCode {
    return json as CountryCode;
}

export function CountryCodeToJSON(value?: CountryCode | null): any {
    return value as any;
}

