/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CraBankIncomeTransaction } from './CraBankIncomeTransaction';
import {
    CraBankIncomeTransactionFromJSON,
    CraBankIncomeTransactionFromJSONTyped,
    CraBankIncomeTransactionToJSON,
} from './CraBankIncomeTransaction';
import type { CreditAmountWithCurrency } from './CreditAmountWithCurrency';
import {
    CreditAmountWithCurrencyFromJSON,
    CreditAmountWithCurrencyFromJSONTyped,
    CreditAmountWithCurrencyToJSON,
} from './CreditAmountWithCurrency';

/**
 * The end user's monthly summary for the income source(s).
 * @export
 * @interface CraBankIncomeHistoricalSummary
 */
export interface CraBankIncomeHistoricalSummary {
    [key: string]: any | any;
    /**
     * Total amount of earnings for the income source(s) of the user for the month in the summary.
     * This can contain multiple amounts, with each amount denominated in one unique currency.
     * @type {Array<CreditAmountWithCurrency>}
     * @memberof CraBankIncomeHistoricalSummary
     */
    total_amounts?: Array<CreditAmountWithCurrency>;
    /**
     * The start date of the period covered in this monthly summary.
     * This date will be the first day of the month, unless the month being covered is a partial month because it is the first month included in the summary and the date range being requested does not begin with the first day of the month.
     * The date will be returned in an ISO 8601 format (YYYY-MM-DD).
     * @type {Date}
     * @memberof CraBankIncomeHistoricalSummary
     */
    start_date?: Date;
    /**
     * The end date of the period included in this monthly summary.
     * This date will be the last day of the month, unless the month being covered is a partial month because it is the last month included in the summary and the date range being requested does not end with the last day of the month.
     * The date will be returned in an ISO 8601 format (YYYY-MM-DD).
     * @type {Date}
     * @memberof CraBankIncomeHistoricalSummary
     */
    end_date?: Date;
    /**
     * 
     * @type {Array<CraBankIncomeTransaction>}
     * @memberof CraBankIncomeHistoricalSummary
     */
    transactions?: Array<CraBankIncomeTransaction>;
}

/**
 * Check if a given object implements the CraBankIncomeHistoricalSummary interface.
 */
export function instanceOfCraBankIncomeHistoricalSummary(value: object): boolean {
    return true;
}

export function CraBankIncomeHistoricalSummaryFromJSON(json: any): CraBankIncomeHistoricalSummary {
    return CraBankIncomeHistoricalSummaryFromJSONTyped(json, false);
}

export function CraBankIncomeHistoricalSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CraBankIncomeHistoricalSummary {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'total_amounts': json['total_amounts'] == null ? undefined : ((json['total_amounts'] as Array<any>).map(CreditAmountWithCurrencyFromJSON)),
        'start_date': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'end_date': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(CraBankIncomeTransactionFromJSON)),
    };
}

export function CraBankIncomeHistoricalSummaryToJSON(value?: CraBankIncomeHistoricalSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'total_amounts': value['total_amounts'] == null ? undefined : ((value['total_amounts'] as Array<any>).map(CreditAmountWithCurrencyToJSON)),
        'start_date': value['start_date'] == null ? undefined : ((value['start_date']).toISOString().substring(0,10)),
        'end_date': value['end_date'] == null ? undefined : ((value['end_date']).toISOString().substring(0,10)),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(CraBankIncomeTransactionToJSON)),
    };
}

