/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The object containing employer data.
 * @export
 * @interface CraBankIncomeEmployer
 */
export interface CraBankIncomeEmployer {
    [key: string]: any | any;
    /**
     * The name of the employer.
     * @type {string}
     * @memberof CraBankIncomeEmployer
     */
    name: string | null;
}

/**
 * Check if a given object implements the CraBankIncomeEmployer interface.
 */
export function instanceOfCraBankIncomeEmployer(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CraBankIncomeEmployerFromJSON(json: any): CraBankIncomeEmployer {
    return CraBankIncomeEmployerFromJSONTyped(json, false);
}

export function CraBankIncomeEmployerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CraBankIncomeEmployer {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
    };
}

export function CraBankIncomeEmployerToJSON(value?: CraBankIncomeEmployer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'name': value['name'],
    };
}

