/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The details of a document income verification in Link
 * @export
 * @interface CreditSessionDocumentIncomeResult
 */
export interface CreditSessionDocumentIncomeResult {
    /**
     * The number of paystubs uploaded by the user.
     * @type {number}
     * @memberof CreditSessionDocumentIncomeResult
     */
    num_paystubs_uploaded: number;
    /**
     * The number of w2s uploaded by the user.
     * @type {number}
     * @memberof CreditSessionDocumentIncomeResult
     */
    num_w2s_uploaded: number;
    /**
     * The number of bank statements uploaded by the user.
     * @type {number}
     * @memberof CreditSessionDocumentIncomeResult
     */
    num_bank_statements_uploaded: number;
    /**
     * The number of 1099s uploaded by the user
     * @type {number}
     * @memberof CreditSessionDocumentIncomeResult
     */
    num_1099s_uploaded: number;
}

/**
 * Check if a given object implements the CreditSessionDocumentIncomeResult interface.
 */
export function instanceOfCreditSessionDocumentIncomeResult(value: object): boolean {
    if (!('num_paystubs_uploaded' in value)) return false;
    if (!('num_w2s_uploaded' in value)) return false;
    if (!('num_bank_statements_uploaded' in value)) return false;
    if (!('num_1099s_uploaded' in value)) return false;
    return true;
}

export function CreditSessionDocumentIncomeResultFromJSON(json: any): CreditSessionDocumentIncomeResult {
    return CreditSessionDocumentIncomeResultFromJSONTyped(json, false);
}

export function CreditSessionDocumentIncomeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditSessionDocumentIncomeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'num_paystubs_uploaded': json['num_paystubs_uploaded'],
        'num_w2s_uploaded': json['num_w2s_uploaded'],
        'num_bank_statements_uploaded': json['num_bank_statements_uploaded'],
        'num_1099s_uploaded': json['num_1099s_uploaded'],
    };
}

export function CreditSessionDocumentIncomeResultToJSON(value?: CreditSessionDocumentIncomeResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'num_paystubs_uploaded': value['num_paystubs_uploaded'],
        'num_w2s_uploaded': value['num_w2s_uploaded'],
        'num_bank_statements_uploaded': value['num_bank_statements_uploaded'],
        'num_1099s_uploaded': value['num_1099s_uploaded'],
    };
}

