/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditBankStatementUploadItem } from './CreditBankStatementUploadItem';
import {
    CreditBankStatementUploadItemFromJSON,
    CreditBankStatementUploadItemFromJSONTyped,
    CreditBankStatementUploadItemToJSON,
} from './CreditBankStatementUploadItem';

/**
 * CreditBankStatementsUploadsGetResponse defines the response schema for `/credit/bank_statements/uploads/get`
 * @export
 * @interface CreditBankStatementsUploadsGetResponse
 */
export interface CreditBankStatementsUploadsGetResponse {
    [key: string]: any | any;
    /**
     * Array of bank statement upload items.
     * @type {Array<CreditBankStatementUploadItem>}
     * @memberof CreditBankStatementsUploadsGetResponse
     */
    items: Array<CreditBankStatementUploadItem>;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof CreditBankStatementsUploadsGetResponse
     */
    request_id: string;
}

/**
 * Check if a given object implements the CreditBankStatementsUploadsGetResponse interface.
 */
export function instanceOfCreditBankStatementsUploadsGetResponse(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function CreditBankStatementsUploadsGetResponseFromJSON(json: any): CreditBankStatementsUploadsGetResponse {
    return CreditBankStatementsUploadsGetResponseFromJSONTyped(json, false);
}

export function CreditBankStatementsUploadsGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBankStatementsUploadsGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'items': ((json['items'] as Array<any>).map(CreditBankStatementUploadItemFromJSON)),
        'request_id': json['request_id'],
    };
}

export function CreditBankStatementsUploadsGetResponseToJSON(value?: CreditBankStatementsUploadsGetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'items': ((value['items'] as Array<any>).map(CreditBankStatementUploadItemToJSON)),
        'request_id': value['request_id'],
    };
}

