/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditFreddieMacLoanIdentifiers } from './CreditFreddieMacLoanIdentifiers';
import {
    CreditFreddieMacLoanIdentifiersFromJSON,
    CreditFreddieMacLoanIdentifiersFromJSONTyped,
    CreditFreddieMacLoanIdentifiersToJSON,
} from './CreditFreddieMacLoanIdentifiers';

/**
 * Information specific to a mortgage loan agreement between one or more borrowers and a mortgage lender.
 * @export
 * @interface CreditFreddieMacLoan
 */
export interface CreditFreddieMacLoan {
    [key: string]: any | any;
    /**
     * 
     * @type {CreditFreddieMacLoanIdentifiers}
     * @memberof CreditFreddieMacLoan
     */
    LOAN_IDENTIFIERS: CreditFreddieMacLoanIdentifiers;
    /**
     * Type of loan. The value can only be "SubjectLoan"
     * @type {string}
     * @memberof CreditFreddieMacLoan
     */
    LoanRoleType: string;
}

/**
 * Check if a given object implements the CreditFreddieMacLoan interface.
 */
export function instanceOfCreditFreddieMacLoan(value: object): boolean {
    if (!('LOAN_IDENTIFIERS' in value)) return false;
    if (!('LoanRoleType' in value)) return false;
    return true;
}

export function CreditFreddieMacLoanFromJSON(json: any): CreditFreddieMacLoan {
    return CreditFreddieMacLoanFromJSONTyped(json, false);
}

export function CreditFreddieMacLoanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditFreddieMacLoan {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'LOAN_IDENTIFIERS': CreditFreddieMacLoanIdentifiersFromJSON(json['LOAN_IDENTIFIERS']),
        'LoanRoleType': json['LoanRoleType'],
    };
}

export function CreditFreddieMacLoanToJSON(value?: CreditFreddieMacLoan | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'LOAN_IDENTIFIERS': CreditFreddieMacLoanIdentifiersToJSON(value['LOAN_IDENTIFIERS']),
        'LoanRoleType': value['LoanRoleType'],
    };
}

