/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A broad categorization of the error. Safe for programmatic use.
 * @export
 */
export const CreditBankIncomeErrorType = {
    InternalServerError: 'INTERNAL_SERVER_ERROR',
    InsufficientCredentials: 'INSUFFICIENT_CREDENTIALS',
    ItemLocked: 'ITEM_LOCKED',
    UserSetupRequired: 'USER_SETUP_REQUIRED',
    CountryNotSupported: 'COUNTRY_NOT_SUPPORTED',
    InstitutionDown: 'INSTITUTION_DOWN',
    InstitutionNoLongerSupported: 'INSTITUTION_NO_LONGER_SUPPORTED',
    InstitutionNotResponding: 'INSTITUTION_NOT_RESPONDING',
    InvalidCredentials: 'INVALID_CREDENTIALS',
    InvalidMfa: 'INVALID_MFA',
    InvalidSendMethod: 'INVALID_SEND_METHOD',
    ItemLoginRequired: 'ITEM_LOGIN_REQUIRED',
    MfaNotSupported: 'MFA_NOT_SUPPORTED',
    NoAccounts: 'NO_ACCOUNTS',
    ItemNotSupported: 'ITEM_NOT_SUPPORTED',
    AccessNotGranted: 'ACCESS_NOT_GRANTED'
} as const;
export type CreditBankIncomeErrorType = typeof CreditBankIncomeErrorType[keyof typeof CreditBankIncomeErrorType];


export function CreditBankIncomeErrorTypeFromJSON(json: any): CreditBankIncomeErrorType {
    return CreditBankIncomeErrorTypeFromJSONTyped(json, false);
}

export function CreditBankIncomeErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBankIncomeErrorType {
    return json as CreditBankIncomeErrorType;
}

export function CreditBankIncomeErrorTypeToJSON(value?: CreditBankIncomeErrorType | null): any {
    return value as any;
}

