/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The details of a Link error.
 * @export
 * @interface CreditSessionError
 */
export interface CreditSessionError {
    /**
     * A broad categorization of the error.
     * @type {string}
     * @memberof CreditSessionError
     */
    error_type?: string;
    /**
     * The particular error code.
     * @type {string}
     * @memberof CreditSessionError
     */
    error_code?: string;
    /**
     * A developer-friendly representation of the error code.
     * @type {string}
     * @memberof CreditSessionError
     */
    error_message?: string;
    /**
     * A user-friendly representation of the error code. `null` if the error is not related to user action.
     * @type {string}
     * @memberof CreditSessionError
     */
    display_message?: string;
}

/**
 * Check if a given object implements the CreditSessionError interface.
 */
export function instanceOfCreditSessionError(value: object): boolean {
    return true;
}

export function CreditSessionErrorFromJSON(json: any): CreditSessionError {
    return CreditSessionErrorFromJSONTyped(json, false);
}

export function CreditSessionErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditSessionError {
    if (json == null) {
        return json;
    }
    return {
        
        'error_type': json['error_type'] == null ? undefined : json['error_type'],
        'error_code': json['error_code'] == null ? undefined : json['error_code'],
        'error_message': json['error_message'] == null ? undefined : json['error_message'],
        'display_message': json['display_message'] == null ? undefined : json['display_message'],
    };
}

export function CreditSessionErrorToJSON(value?: CreditSessionError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error_type': value['error_type'],
        'error_code': value['error_code'],
        'error_message': value['error_message'],
        'display_message': value['display_message'],
    };
}

