/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The income category. Note that the `CASH` value has been deprecated and is used only for existing legacy implementations. It has been replaced by the new categories `CASH_DEPOSIT` (representing cash or check deposits) and `TRANSFER_FROM_APPLICATION` (representing cash transfers originating from apps, such as Zelle or Venmo).
 * @export
 */
export const CreditBankIncomeCategory = {
    Salary: 'SALARY',
    Unemployment: 'UNEMPLOYMENT',
    Cash: 'CASH',
    GigEconomy: 'GIG_ECONOMY',
    Rental: 'RENTAL',
    ChildSupport: 'CHILD_SUPPORT',
    Military: 'MILITARY',
    Retirement: 'RETIREMENT',
    LongTermDisability: 'LONG_TERM_DISABILITY',
    BankInterest: 'BANK_INTEREST',
    CashDeposit: 'CASH_DEPOSIT',
    TransferFromApplication: 'TRANSFER_FROM_APPLICATION',
    TaxRefund: 'TAX_REFUND',
    BenefitOther: 'BENEFIT_OTHER',
    Other: 'OTHER'
} as const;
export type CreditBankIncomeCategory = typeof CreditBankIncomeCategory[keyof typeof CreditBankIncomeCategory];


export function CreditBankIncomeCategoryFromJSON(json: any): CreditBankIncomeCategory {
    return CreditBankIncomeCategoryFromJSONTyped(json, false);
}

export function CreditBankIncomeCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBankIncomeCategory {
    return json as CreditBankIncomeCategory;
}

export function CreditBankIncomeCategoryToJSON(value?: CreditBankIncomeCategory | null): any {
    return value as any;
}

