/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DepositSwitchTokenCreateRequest defines the request schema for `/deposit_switch/token/create`
 * @export
 * @interface DepositSwitchTokenCreateRequest
 */
export interface DepositSwitchTokenCreateRequest {
    /**
     * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
     * @type {string}
     * @memberof DepositSwitchTokenCreateRequest
     */
    client_id?: string;
    /**
     * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
     * @type {string}
     * @memberof DepositSwitchTokenCreateRequest
     */
    secret?: string;
    /**
     * The ID of the deposit switch
     * @type {string}
     * @memberof DepositSwitchTokenCreateRequest
     */
    deposit_switch_id: string;
}

/**
 * Check if a given object implements the DepositSwitchTokenCreateRequest interface.
 */
export function instanceOfDepositSwitchTokenCreateRequest(value: object): boolean {
    if (!('deposit_switch_id' in value)) return false;
    return true;
}

export function DepositSwitchTokenCreateRequestFromJSON(json: any): DepositSwitchTokenCreateRequest {
    return DepositSwitchTokenCreateRequestFromJSONTyped(json, false);
}

export function DepositSwitchTokenCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositSwitchTokenCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'deposit_switch_id': json['deposit_switch_id'],
    };
}

export function DepositSwitchTokenCreateRequestToJSON(value?: DepositSwitchTokenCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_id': value['client_id'],
        'secret': value['secret'],
        'deposit_switch_id': value['deposit_switch_id'],
    };
}

