/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Commonly used term to describe the earning line item.
 * @export
 */
export const EarningsBreakdownCanonicalDescription = {
    Bonus: 'BONUS',
    Commission: 'COMMISSION',
    Overtime: 'OVERTIME',
    PaidTimeOff: 'PAID TIME OFF',
    RegularPay: 'REGULAR PAY',
    Vacation: 'VACATION',
    BasicAllowanceHousing: 'BASIC ALLOWANCE HOUSING',
    BasicAllowanceSubsistence: 'BASIC ALLOWANCE SUBSISTENCE',
    Other: 'OTHER',
    Null: 'null'
} as const;
export type EarningsBreakdownCanonicalDescription = typeof EarningsBreakdownCanonicalDescription[keyof typeof EarningsBreakdownCanonicalDescription];


export function EarningsBreakdownCanonicalDescriptionFromJSON(json: any): EarningsBreakdownCanonicalDescription {
    return EarningsBreakdownCanonicalDescriptionFromJSONTyped(json, false);
}

export function EarningsBreakdownCanonicalDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EarningsBreakdownCanonicalDescription {
    return json as EarningsBreakdownCanonicalDescription;
}

export function EarningsBreakdownCanonicalDescriptionToJSON(value?: EarningsBreakdownCanonicalDescription | null): any {
    return value as any;
}

