/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pay } from './Pay';
import {
    PayFromJSON,
    PayFromJSONTyped,
    PayToJSON,
} from './Pay';

/**
 * An object representing both the current pay period and year to date amount for an earning category.
 * @export
 * @interface EarningsTotal
 */
export interface EarningsTotal {
    [key: string]: any | any;
    /**
     * Total amount of the earnings for this pay period
     * @type {number}
     * @memberof EarningsTotal
     */
    current_amount?: number;
    /**
     * 
     * @type {Pay}
     * @memberof EarningsTotal
     * @deprecated
     */
    current_pay?: Pay;
    /**
     * 
     * @type {Pay}
     * @memberof EarningsTotal
     * @deprecated
     */
    ytd_pay?: Pay;
    /**
     * Total number of hours worked for this pay period
     * @type {number}
     * @memberof EarningsTotal
     */
    hours?: number;
    /**
     * The ISO-4217 currency code of the line item. Always `null` if `unofficial_currency_code` is non-null.
     * @type {string}
     * @memberof EarningsTotal
     */
    iso_currency_code?: string;
    /**
     * The unofficial currency code associated with the security. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
     * 
     * See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
     * @type {string}
     * @memberof EarningsTotal
     */
    unofficial_currency_code?: string;
    /**
     * The total year-to-date amount of the earnings
     * @type {number}
     * @memberof EarningsTotal
     */
    ytd_amount?: number;
}

/**
 * Check if a given object implements the EarningsTotal interface.
 */
export function instanceOfEarningsTotal(value: object): boolean {
    return true;
}

export function EarningsTotalFromJSON(json: any): EarningsTotal {
    return EarningsTotalFromJSONTyped(json, false);
}

export function EarningsTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): EarningsTotal {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'current_amount': json['current_amount'] == null ? undefined : json['current_amount'],
        'current_pay': json['current_pay'] == null ? undefined : PayFromJSON(json['current_pay']),
        'ytd_pay': json['ytd_pay'] == null ? undefined : PayFromJSON(json['ytd_pay']),
        'hours': json['hours'] == null ? undefined : json['hours'],
        'iso_currency_code': json['iso_currency_code'] == null ? undefined : json['iso_currency_code'],
        'unofficial_currency_code': json['unofficial_currency_code'] == null ? undefined : json['unofficial_currency_code'],
        'ytd_amount': json['ytd_amount'] == null ? undefined : json['ytd_amount'],
    };
}

export function EarningsTotalToJSON(value?: EarningsTotal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'current_amount': value['current_amount'],
        'current_pay': PayToJSON(value['current_pay']),
        'ytd_pay': PayToJSON(value['ytd_pay']),
        'hours': value['hours'],
        'iso_currency_code': value['iso_currency_code'],
        'unofficial_currency_code': value['unofficial_currency_code'],
        'ytd_amount': value['ytd_amount'],
    };
}

