/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchSummaryCode } from './MatchSummaryCode';
import {
    MatchSummaryCodeFromJSON,
    MatchSummaryCodeFromJSONTyped,
    MatchSummaryCodeToJSON,
} from './MatchSummaryCode';

/**
 * Analysis information describing why a screening hit matched the provided entity information
 * @export
 * @interface EntityScreeningHitAnalysis
 */
export interface EntityScreeningHitAnalysis {
    [key: string]: any | any;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    documents?: MatchSummaryCode;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    email_addresses?: MatchSummaryCode;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    locations?: MatchSummaryCode;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    names?: MatchSummaryCode;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    phone_numbers?: MatchSummaryCode;
    /**
     * 
     * @type {MatchSummaryCode}
     * @memberof EntityScreeningHitAnalysis
     */
    urls?: MatchSummaryCode;
    /**
     * The version of the entity screening's `search_terms` that were compared when the entity screening hit was added. entity screening hits are immutable once they have been reviewed. If changes are detected due to updates to the entity screening's `search_terms`, the associated entity program, or the list's source data prior to review, the entity screening hit will be updated to reflect those changes.
     * @type {number}
     * @memberof EntityScreeningHitAnalysis
     */
    search_terms_version: number;
}

/**
 * Check if a given object implements the EntityScreeningHitAnalysis interface.
 */
export function instanceOfEntityScreeningHitAnalysis(value: object): boolean {
    if (!('search_terms_version' in value)) return false;
    return true;
}

export function EntityScreeningHitAnalysisFromJSON(json: any): EntityScreeningHitAnalysis {
    return EntityScreeningHitAnalysisFromJSONTyped(json, false);
}

export function EntityScreeningHitAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityScreeningHitAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'documents': json['documents'] == null ? undefined : MatchSummaryCodeFromJSON(json['documents']),
        'email_addresses': json['email_addresses'] == null ? undefined : MatchSummaryCodeFromJSON(json['email_addresses']),
        'locations': json['locations'] == null ? undefined : MatchSummaryCodeFromJSON(json['locations']),
        'names': json['names'] == null ? undefined : MatchSummaryCodeFromJSON(json['names']),
        'phone_numbers': json['phone_numbers'] == null ? undefined : MatchSummaryCodeFromJSON(json['phone_numbers']),
        'urls': json['urls'] == null ? undefined : MatchSummaryCodeFromJSON(json['urls']),
        'search_terms_version': json['search_terms_version'],
    };
}

export function EntityScreeningHitAnalysisToJSON(value?: EntityScreeningHitAnalysis | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'documents': MatchSummaryCodeToJSON(value['documents']),
        'email_addresses': MatchSummaryCodeToJSON(value['email_addresses']),
        'locations': MatchSummaryCodeToJSON(value['locations']),
        'names': MatchSummaryCodeToJSON(value['names']),
        'phone_numbers': MatchSummaryCodeToJSON(value['phone_numbers']),
        'urls': MatchSummaryCodeToJSON(value['urls']),
        'search_terms_version': value['search_terms_version'],
    };
}

