/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Search terms associated with an entity used for searching against watchlists
 * @export
 * @interface EntityWatchlistScreeningSearchTerms
 */
export interface EntityWatchlistScreeningSearchTerms {
    [key: string]: any | any;
    /**
     * ID of the associated entity program.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    entity_watchlist_program_id: string;
    /**
     * The name of the organization being screened.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    legal_name: string;
    /**
     * The numeric or alphanumeric identifier associated with this document.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    document_number: string | null;
    /**
     * A valid email address.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    email_address: string | null;
    /**
     * Valid, capitalized, two-letter ISO code representing the country of this object. Must be in ISO 3166-1 alpha-2 form.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    country: string | null;
    /**
     * A phone number in E.164 format.
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    phone_number: string | null;
    /**
     * An 'http' or 'https' URL (must begin with either of those).
     * @type {string}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    url: string | null;
    /**
     * The current version of the search terms. Starts at `1` and increments with each edit to `search_terms`.
     * @type {number}
     * @memberof EntityWatchlistScreeningSearchTerms
     */
    version: number;
}

/**
 * Check if a given object implements the EntityWatchlistScreeningSearchTerms interface.
 */
export function instanceOfEntityWatchlistScreeningSearchTerms(value: object): boolean {
    if (!('entity_watchlist_program_id' in value)) return false;
    if (!('legal_name' in value)) return false;
    if (!('document_number' in value)) return false;
    if (!('email_address' in value)) return false;
    if (!('country' in value)) return false;
    if (!('phone_number' in value)) return false;
    if (!('url' in value)) return false;
    if (!('version' in value)) return false;
    return true;
}

export function EntityWatchlistScreeningSearchTermsFromJSON(json: any): EntityWatchlistScreeningSearchTerms {
    return EntityWatchlistScreeningSearchTermsFromJSONTyped(json, false);
}

export function EntityWatchlistScreeningSearchTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityWatchlistScreeningSearchTerms {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'entity_watchlist_program_id': json['entity_watchlist_program_id'],
        'legal_name': json['legal_name'],
        'document_number': json['document_number'],
        'email_address': json['email_address'],
        'country': json['country'],
        'phone_number': json['phone_number'],
        'url': json['url'],
        'version': json['version'],
    };
}

export function EntityWatchlistScreeningSearchTermsToJSON(value?: EntityWatchlistScreeningSearchTerms | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'entity_watchlist_program_id': value['entity_watchlist_program_id'],
        'legal_name': value['legal_name'],
        'document_number': value['document_number'],
        'email_address': value['email_address'],
        'country': value['country'],
        'phone_number': value['phone_number'],
        'url': value['url'],
        'version': value['version'],
    };
}

