/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A description of whether the associated document was expired when the verification was performed.
 * 
 * Note: In the case where an expiration date is not present on the document or failed to be extracted, this value will be `no_data`.
 * @export
 */
export const ExpirationDate = {
    NotExpired: 'not_expired',
    Expired: 'expired',
    NoData: 'no_data'
} as const;
export type ExpirationDate = typeof ExpirationDate[keyof typeof ExpirationDate];


export function ExpirationDateFromJSON(json: any): ExpirationDate {
    return ExpirationDateFromJSONTyped(json, false);
}

export function ExpirationDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpirationDate {
    return json as ExpirationDate;
}

export function ExpirationDateToJSON(value?: ExpirationDate | null): any {
    return value as any;
}

