/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipientBACSNullable } from './RecipientBACSNullable';
import {
    RecipientBACSNullableFromJSON,
    RecipientBACSNullableFromJSONTyped,
    RecipientBACSNullableToJSON,
} from './RecipientBACSNullable';

/**
 * Details about external payment refund
 * @export
 * @interface ExternalPaymentRefundDetails
 */
export interface ExternalPaymentRefundDetails {
    /**
     * The name of the account holder.
     * @type {string}
     * @memberof ExternalPaymentRefundDetails
     */
    name: string;
    /**
     * The International Bank Account Number (IBAN) for the account.
     * @type {string}
     * @memberof ExternalPaymentRefundDetails
     */
    iban: string | null;
    /**
     * 
     * @type {RecipientBACSNullable}
     * @memberof ExternalPaymentRefundDetails
     */
    bacs: RecipientBACSNullable | null;
}

/**
 * Check if a given object implements the ExternalPaymentRefundDetails interface.
 */
export function instanceOfExternalPaymentRefundDetails(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('iban' in value)) return false;
    if (!('bacs' in value)) return false;
    return true;
}

export function ExternalPaymentRefundDetailsFromJSON(json: any): ExternalPaymentRefundDetails {
    return ExternalPaymentRefundDetailsFromJSONTyped(json, false);
}

export function ExternalPaymentRefundDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalPaymentRefundDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'iban': json['iban'],
        'bacs': RecipientBACSNullableFromJSON(json['bacs']),
    };
}

export function ExternalPaymentRefundDetailsToJSON(value?: ExternalPaymentRefundDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'iban': value['iban'],
        'bacs': RecipientBACSNullableToJSON(value['bacs']),
    };
}

