/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Priority of notification
 * @export
 */
export const FDXNotificationPriority = {
    High: 'HIGH',
    Medium: 'MEDIUM',
    Low: 'LOW'
} as const;
export type FDXNotificationPriority = typeof FDXNotificationPriority[keyof typeof FDXNotificationPriority];


export function FDXNotificationPriorityFromJSON(json: any): FDXNotificationPriority {
    return FDXNotificationPriorityFromJSONTyped(json, false);
}

export function FDXNotificationPriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FDXNotificationPriority {
    return json as FDXNotificationPriority;
}

export function FDXNotificationPriorityToJSON(value?: FDXNotificationPriority | null): any {
    return value as any;
}

