/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchSummary } from './MatchSummary';
import {
    MatchSummaryFromJSON,
    MatchSummaryFromJSONTyped,
    MatchSummaryToJSON,
} from './MatchSummary';
import type { WatchlistScreeningHitLocations } from './WatchlistScreeningHitLocations';
import {
    WatchlistScreeningHitLocationsFromJSON,
    WatchlistScreeningHitLocationsFromJSONTyped,
    WatchlistScreeningHitLocationsToJSON,
} from './WatchlistScreeningHitLocations';

/**
 * Analyzed location information for the associated hit
 * @export
 * @interface GenericScreeningHitLocationItems
 */
export interface GenericScreeningHitLocationItems {
    [key: string]: any | any;
    /**
     * 
     * @type {MatchSummary}
     * @memberof GenericScreeningHitLocationItems
     */
    analysis?: MatchSummary;
    /**
     * 
     * @type {WatchlistScreeningHitLocations}
     * @memberof GenericScreeningHitLocationItems
     */
    data?: WatchlistScreeningHitLocations;
}

/**
 * Check if a given object implements the GenericScreeningHitLocationItems interface.
 */
export function instanceOfGenericScreeningHitLocationItems(value: object): boolean {
    return true;
}

export function GenericScreeningHitLocationItemsFromJSON(json: any): GenericScreeningHitLocationItems {
    return GenericScreeningHitLocationItemsFromJSONTyped(json, false);
}

export function GenericScreeningHitLocationItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericScreeningHitLocationItems {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'analysis': json['analysis'] == null ? undefined : MatchSummaryFromJSON(json['analysis']),
        'data': json['data'] == null ? undefined : WatchlistScreeningHitLocationsFromJSON(json['data']),
    };
}

export function GenericScreeningHitLocationItemsToJSON(value?: GenericScreeningHitLocationItems | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'analysis': MatchSummaryToJSON(value['analysis']),
        'data': WatchlistScreeningHitLocationsToJSON(value['data']),
    };
}

