/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEnvironmentValues } from './WebhookEnvironmentValues';
import {
    WebhookEnvironmentValuesFromJSON,
    WebhookEnvironmentValuesFromJSONTyped,
    WebhookEnvironmentValuesToJSON,
} from './WebhookEnvironmentValues';

/**
 * Fired when the status of an identity verification has been updated, which can be triggered via the dashboard or the API.
 * @export
 * @interface IdentityVerificationStatusUpdatedWebhook
 */
export interface IdentityVerificationStatusUpdatedWebhook {
    [key: string]: any | any;
    /**
     * `IDENTITY_VERIFICATION`
     * @type {string}
     * @memberof IdentityVerificationStatusUpdatedWebhook
     */
    webhook_type: string;
    /**
     * `STATUS_UPDATED`
     * @type {string}
     * @memberof IdentityVerificationStatusUpdatedWebhook
     */
    webhook_code: string;
    /**
     * The ID of the associated Identity Verification attempt.
     * @type {string}
     * @memberof IdentityVerificationStatusUpdatedWebhook
     */
    identity_verification_id: string;
    /**
     * 
     * @type {WebhookEnvironmentValues}
     * @memberof IdentityVerificationStatusUpdatedWebhook
     */
    environment: WebhookEnvironmentValues;
}

/**
 * Check if a given object implements the IdentityVerificationStatusUpdatedWebhook interface.
 */
export function instanceOfIdentityVerificationStatusUpdatedWebhook(value: object): boolean {
    if (!('webhook_type' in value)) return false;
    if (!('webhook_code' in value)) return false;
    if (!('identity_verification_id' in value)) return false;
    if (!('environment' in value)) return false;
    return true;
}

export function IdentityVerificationStatusUpdatedWebhookFromJSON(json: any): IdentityVerificationStatusUpdatedWebhook {
    return IdentityVerificationStatusUpdatedWebhookFromJSONTyped(json, false);
}

export function IdentityVerificationStatusUpdatedWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityVerificationStatusUpdatedWebhook {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'webhook_type': json['webhook_type'],
        'webhook_code': json['webhook_code'],
        'identity_verification_id': json['identity_verification_id'],
        'environment': WebhookEnvironmentValuesFromJSON(json['environment']),
    };
}

export function IdentityVerificationStatusUpdatedWebhookToJSON(value?: IdentityVerificationStatusUpdatedWebhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'webhook_type': value['webhook_type'],
        'webhook_code': value['webhook_code'],
        'identity_verification_id': value['identity_verification_id'],
        'environment': WebhookEnvironmentValuesToJSON(value['environment']),
    };
}

