/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * You can use this field to pre-populate the user's legal name; if it is provided here, they will not be prompted to enter their name in the identity verification attempt.
 * @export
 * @interface IdentityVerificationRequestUserName
 */
export interface IdentityVerificationRequestUserName {
    /**
     * A string with at least one non-whitespace character, with a max length of 100 characters.
     * @type {string}
     * @memberof IdentityVerificationRequestUserName
     */
    given_name: string;
    /**
     * A string with at least one non-whitespace character, with a max length of 100 characters.
     * @type {string}
     * @memberof IdentityVerificationRequestUserName
     */
    family_name: string;
}

/**
 * Check if a given object implements the IdentityVerificationRequestUserName interface.
 */
export function instanceOfIdentityVerificationRequestUserName(value: object): boolean {
    if (!('given_name' in value)) return false;
    if (!('family_name' in value)) return false;
    return true;
}

export function IdentityVerificationRequestUserNameFromJSON(json: any): IdentityVerificationRequestUserName {
    return IdentityVerificationRequestUserNameFromJSONTyped(json, false);
}

export function IdentityVerificationRequestUserNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityVerificationRequestUserName {
    if (json == null) {
        return json;
    }
    return {
        
        'given_name': json['given_name'],
        'family_name': json['family_name'],
    };
}

export function IdentityVerificationRequestUserNameToJSON(value?: IdentityVerificationRequestUserName | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'given_name': value['given_name'],
        'family_name': value['family_name'],
    };
}

