/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaystubOverride } from './PaystubOverride';
import {
    PaystubOverrideFromJSON,
    PaystubOverrideFromJSONTyped,
    PaystubOverrideToJSON,
} from './PaystubOverride';

/**
 * Specify payroll data on the account.
 * @export
 * @interface IncomeOverride
 */
export interface IncomeOverride {
    /**
     * A list of paystubs associated with the account.
     * @type {Array<PaystubOverride>}
     * @memberof IncomeOverride
     */
    paystubs?: Array<PaystubOverride>;
}

/**
 * Check if a given object implements the IncomeOverride interface.
 */
export function instanceOfIncomeOverride(value: object): boolean {
    return true;
}

export function IncomeOverrideFromJSON(json: any): IncomeOverride {
    return IncomeOverrideFromJSONTyped(json, false);
}

export function IncomeOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'paystubs': json['paystubs'] == null ? undefined : ((json['paystubs'] as Array<any>).map(PaystubOverrideFromJSON)),
    };
}

export function IncomeOverrideToJSON(value?: IncomeOverride | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'paystubs': value['paystubs'] == null ? undefined : ((value['paystubs'] as Array<any>).map(PaystubOverrideToJSON)),
    };
}

