/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The types of source income data that users should be able to share
 * @export
 */
export const IncomeVerificationSourceType = {
    Bank: 'bank',
    Payroll: 'payroll'
} as const;
export type IncomeVerificationSourceType = typeof IncomeVerificationSourceType[keyof typeof IncomeVerificationSourceType];


export function IncomeVerificationSourceTypeFromJSON(json: any): IncomeVerificationSourceType {
    return IncomeVerificationSourceTypeFromJSONTyped(json, false);
}

export function IncomeVerificationSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeVerificationSourceType {
    return json as IncomeVerificationSourceType;
}

export function IncomeVerificationSourceTypeToJSON(value?: IncomeVerificationSourceType | null): any {
    return value as any;
}

