/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional arguments for `/income/verification/create`
 * @export
 * @interface IncomeVerificationCreateRequestOptions
 */
export interface IncomeVerificationCreateRequestOptions {
    /**
     * An array of access tokens corresponding to the Items that will be cross-referenced with the product data. Plaid will attempt to correlate transaction history from these Items with data from the user's paystub, such as date and amount. If the `transactions` product was not initialized for the Items during Link, it will be initialized after this Link session.
     * @type {Array<string>}
     * @memberof IncomeVerificationCreateRequestOptions
     */
    access_tokens?: Array<string>;
}

/**
 * Check if a given object implements the IncomeVerificationCreateRequestOptions interface.
 */
export function instanceOfIncomeVerificationCreateRequestOptions(value: object): boolean {
    return true;
}

export function IncomeVerificationCreateRequestOptionsFromJSON(json: any): IncomeVerificationCreateRequestOptions {
    return IncomeVerificationCreateRequestOptionsFromJSONTyped(json, false);
}

export function IncomeVerificationCreateRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeVerificationCreateRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'access_tokens': json['access_tokens'] == null ? undefined : json['access_tokens'],
    };
}

export function IncomeVerificationCreateRequestOptionsToJSON(value?: IncomeVerificationCreateRequestOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_tokens': value['access_tokens'],
    };
}

