/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEnvironmentValues } from './WebhookEnvironmentValues';
import {
    WebhookEnvironmentValuesFromJSON,
    WebhookEnvironmentValuesFromJSONTyped,
    WebhookEnvironmentValuesToJSON,
} from './WebhookEnvironmentValues';

/**
 * Fired when the attempt to refresh Payroll Income data for a user via `/credit/payroll_income/refresh` failed because the user must re-connect their payroll account.
 * @export
 * @interface IncomeVerificationRefreshReconnectNeededWebhook
 */
export interface IncomeVerificationRefreshReconnectNeededWebhook {
    [key: string]: any | any;
    /**
     * `INCOME`
     * @type {string}
     * @memberof IncomeVerificationRefreshReconnectNeededWebhook
     */
    webhook_type: string;
    /**
     * `INCOME_VERIFICATION_REFRESH_RECONNECT_NEEDED`
     * @type {string}
     * @memberof IncomeVerificationRefreshReconnectNeededWebhook
     */
    webhook_code: string;
    /**
     * The `user_id` corresponding to the user the webhook has fired for.
     * @type {string}
     * @memberof IncomeVerificationRefreshReconnectNeededWebhook
     */
    user_id: string;
    /**
     * 
     * @type {WebhookEnvironmentValues}
     * @memberof IncomeVerificationRefreshReconnectNeededWebhook
     */
    environment: WebhookEnvironmentValues;
}

/**
 * Check if a given object implements the IncomeVerificationRefreshReconnectNeededWebhook interface.
 */
export function instanceOfIncomeVerificationRefreshReconnectNeededWebhook(value: object): boolean {
    if (!('webhook_type' in value)) return false;
    if (!('webhook_code' in value)) return false;
    if (!('user_id' in value)) return false;
    if (!('environment' in value)) return false;
    return true;
}

export function IncomeVerificationRefreshReconnectNeededWebhookFromJSON(json: any): IncomeVerificationRefreshReconnectNeededWebhook {
    return IncomeVerificationRefreshReconnectNeededWebhookFromJSONTyped(json, false);
}

export function IncomeVerificationRefreshReconnectNeededWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeVerificationRefreshReconnectNeededWebhook {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'webhook_type': json['webhook_type'],
        'webhook_code': json['webhook_code'],
        'user_id': json['user_id'],
        'environment': WebhookEnvironmentValuesFromJSON(json['environment']),
    };
}

export function IncomeVerificationRefreshReconnectNeededWebhookToJSON(value?: IncomeVerificationRefreshReconnectNeededWebhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'webhook_type': value['webhook_type'],
        'webhook_code': value['webhook_code'],
        'user_id': value['user_id'],
        'environment': WebhookEnvironmentValuesToJSON(value['environment']),
    };
}

