/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of income. Possible values include:
 *   `"regular"`: regular income
 *   `"overtime"`: overtime income
 *   `"bonus"`: bonus income
 * @export
 */
export const IncomeBreakdownType = {
    Bonus: 'bonus',
    Overtime: 'overtime',
    Regular: 'regular',
    Null: 'null'
} as const;
export type IncomeBreakdownType = typeof IncomeBreakdownType[keyof typeof IncomeBreakdownType];


export function IncomeBreakdownTypeFromJSON(json: any): IncomeBreakdownType {
    return IncomeBreakdownTypeFromJSONTyped(json, false);
}

export function IncomeBreakdownTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeBreakdownType {
    return json as IncomeBreakdownType;
}

export function IncomeBreakdownTypeToJSON(value?: IncomeBreakdownType | null): any {
    return value as any;
}

