/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidError } from './PlaidError';
import {
    PlaidErrorFromJSON,
    PlaidErrorFromJSONTyped,
    PlaidErrorToJSON,
} from './PlaidError';
import type { WebhookEnvironmentValues } from './WebhookEnvironmentValues';
import {
    WebhookEnvironmentValuesFromJSON,
    WebhookEnvironmentValuesFromJSONTyped,
    WebhookEnvironmentValuesToJSON,
} from './WebhookEnvironmentValues';

/**
 * Fired when new transactions have been detected on an investment account.
 * @export
 * @interface InvestmentsDefaultUpdateWebhook
 */
export interface InvestmentsDefaultUpdateWebhook {
    [key: string]: any | any;
    /**
     * `INVESTMENTS_TRANSACTIONS`
     * @type {string}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    webhook_type: string;
    /**
     * `DEFAULT_UPDATE`
     * @type {string}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    webhook_code: string;
    /**
     * The `item_id` of the Item associated with this webhook, warning, or error
     * @type {string}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    item_id: string;
    /**
     * 
     * @type {PlaidError}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    error?: PlaidError;
    /**
     * The number of new transactions reported since the last time this webhook was fired.
     * @type {number}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    new_investments_transactions: number;
    /**
     * The number of canceled transactions reported since the last time this webhook was fired.
     * @type {number}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    canceled_investments_transactions: number;
    /**
     * 
     * @type {WebhookEnvironmentValues}
     * @memberof InvestmentsDefaultUpdateWebhook
     */
    environment: WebhookEnvironmentValues;
}

/**
 * Check if a given object implements the InvestmentsDefaultUpdateWebhook interface.
 */
export function instanceOfInvestmentsDefaultUpdateWebhook(value: object): boolean {
    if (!('webhook_type' in value)) return false;
    if (!('webhook_code' in value)) return false;
    if (!('item_id' in value)) return false;
    if (!('new_investments_transactions' in value)) return false;
    if (!('canceled_investments_transactions' in value)) return false;
    if (!('environment' in value)) return false;
    return true;
}

export function InvestmentsDefaultUpdateWebhookFromJSON(json: any): InvestmentsDefaultUpdateWebhook {
    return InvestmentsDefaultUpdateWebhookFromJSONTyped(json, false);
}

export function InvestmentsDefaultUpdateWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvestmentsDefaultUpdateWebhook {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'webhook_type': json['webhook_type'],
        'webhook_code': json['webhook_code'],
        'item_id': json['item_id'],
        'error': json['error'] == null ? undefined : PlaidErrorFromJSON(json['error']),
        'new_investments_transactions': json['new_investments_transactions'],
        'canceled_investments_transactions': json['canceled_investments_transactions'],
        'environment': WebhookEnvironmentValuesFromJSON(json['environment']),
    };
}

export function InvestmentsDefaultUpdateWebhookToJSON(value?: InvestmentsDefaultUpdateWebhook | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'webhook_type': value['webhook_type'],
        'webhook_code': value['webhook_code'],
        'item_id': value['item_id'],
        'error': PlaidErrorToJSON(value['error']),
        'new_investments_transactions': value['new_investments_transactions'],
        'canceled_investments_transactions': value['canceled_investments_transactions'],
        'environment': WebhookEnvironmentValuesToJSON(value['environment']),
    };
}

