/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvestmentAccountSubtype } from './InvestmentAccountSubtype';
import {
    InvestmentAccountSubtypeFromJSON,
    InvestmentAccountSubtypeFromJSONTyped,
    InvestmentAccountSubtypeToJSON,
} from './InvestmentAccountSubtype';

/**
 * A filter to apply to `investment`-type accounts (or `brokerage`-type accounts for API versions 2018-05-22 and earlier).
 * @export
 * @interface InvestmentFilter
 */
export interface InvestmentFilter {
    [key: string]: any | any;
    /**
     * An array of account subtypes to display in Link. If not specified, all account subtypes will be shown. For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#account-type-schema). 
     * @type {Array<InvestmentAccountSubtype>}
     * @memberof InvestmentFilter
     */
    account_subtypes: Array<InvestmentAccountSubtype>;
}

/**
 * Check if a given object implements the InvestmentFilter interface.
 */
export function instanceOfInvestmentFilter(value: object): boolean {
    if (!('account_subtypes' in value)) return false;
    return true;
}

export function InvestmentFilterFromJSON(json: any): InvestmentFilter {
    return InvestmentFilterFromJSONTyped(json, false);
}

export function InvestmentFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvestmentFilter {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'account_subtypes': ((json['account_subtypes'] as Array<any>).map(InvestmentAccountSubtypeFromJSON)),
    };
}

export function InvestmentFilterToJSON(value?: InvestmentFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'account_subtypes': ((value['account_subtypes'] as Array<any>).map(InvestmentAccountSubtypeToJSON)),
    };
}

