/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about the last successful and failed transactions update for the Item.
 * @export
 * @interface ItemStatusTransactions
 */
export interface ItemStatusTransactions {
    [key: string]: any | any;
    /**
     * [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last successful transactions update for the Item. The status will update each time Plaid successfully connects with the institution, regardless of whether any new data is available in the update.
     * @type {Date}
     * @memberof ItemStatusTransactions
     */
    last_successful_update?: Date;
    /**
     * [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last failed transactions update for the Item. The status will update each time Plaid fails an attempt to connect with the institution, regardless of whether any new data is available in the update.
     * @type {Date}
     * @memberof ItemStatusTransactions
     */
    last_failed_update?: Date;
}

/**
 * Check if a given object implements the ItemStatusTransactions interface.
 */
export function instanceOfItemStatusTransactions(value: object): boolean {
    return true;
}

export function ItemStatusTransactionsFromJSON(json: any): ItemStatusTransactions {
    return ItemStatusTransactionsFromJSONTyped(json, false);
}

export function ItemStatusTransactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemStatusTransactions {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'last_successful_update': json['last_successful_update'] == null ? undefined : (new Date(json['last_successful_update'])),
        'last_failed_update': json['last_failed_update'] == null ? undefined : (new Date(json['last_failed_update'])),
    };
}

export function ItemStatusTransactionsToJSON(value?: ItemStatusTransactions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'last_successful_update': value['last_successful_update'] == null ? undefined : ((value['last_successful_update'] as any).toISOString()),
        'last_failed_update': value['last_failed_update'] == null ? undefined : ((value['last_failed_update'] as any).toISOString()),
    };
}

