/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemStatusInvestments } from './ItemStatusInvestments';
import {
    ItemStatusInvestmentsFromJSON,
    ItemStatusInvestmentsFromJSONTyped,
    ItemStatusInvestmentsToJSON,
} from './ItemStatusInvestments';
import type { ItemStatusLastWebhook } from './ItemStatusLastWebhook';
import {
    ItemStatusLastWebhookFromJSON,
    ItemStatusLastWebhookFromJSONTyped,
    ItemStatusLastWebhookToJSON,
} from './ItemStatusLastWebhook';
import type { ItemStatusTransactions } from './ItemStatusTransactions';
import {
    ItemStatusTransactionsFromJSON,
    ItemStatusTransactionsFromJSONTyped,
    ItemStatusTransactionsToJSON,
} from './ItemStatusTransactions';

/**
 * An object with information about the status of the Item.
 * @export
 * @interface ItemStatus
 */
export interface ItemStatus {
    [key: string]: any | any;
    /**
     * 
     * @type {ItemStatusInvestments}
     * @memberof ItemStatus
     */
    investments?: ItemStatusInvestments;
    /**
     * 
     * @type {ItemStatusTransactions}
     * @memberof ItemStatus
     */
    transactions?: ItemStatusTransactions;
    /**
     * 
     * @type {ItemStatusLastWebhook}
     * @memberof ItemStatus
     */
    last_webhook?: ItemStatusLastWebhook;
}

/**
 * Check if a given object implements the ItemStatus interface.
 */
export function instanceOfItemStatus(value: object): boolean {
    return true;
}

export function ItemStatusFromJSON(json: any): ItemStatus {
    return ItemStatusFromJSONTyped(json, false);
}

export function ItemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemStatus {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'investments': json['investments'] == null ? undefined : ItemStatusInvestmentsFromJSON(json['investments']),
        'transactions': json['transactions'] == null ? undefined : ItemStatusTransactionsFromJSON(json['transactions']),
        'last_webhook': json['last_webhook'] == null ? undefined : ItemStatusLastWebhookFromJSON(json['last_webhook']),
    };
}

export function ItemStatusToJSON(value?: ItemStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'investments': ItemStatusInvestmentsToJSON(value['investments']),
        'transactions': ItemStatusTransactionsToJSON(value['transactions']),
        'last_webhook': ItemStatusLastWebhookToJSON(value['last_webhook']),
    };
}

