/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectedApplication } from './ConnectedApplication';
import {
    ConnectedApplicationFromJSON,
    ConnectedApplicationFromJSONTyped,
    ConnectedApplicationToJSON,
} from './ConnectedApplication';

/**
 * Describes the connected application for a particular end user.
 * @export
 * @interface ItemApplicationListResponse
 */
export interface ItemApplicationListResponse {
    [key: string]: any | any;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof ItemApplicationListResponse
     */
    request_id?: string;
    /**
     * A list of connected applications.
     * @type {Array<ConnectedApplication>}
     * @memberof ItemApplicationListResponse
     */
    applications: Array<ConnectedApplication>;
}

/**
 * Check if a given object implements the ItemApplicationListResponse interface.
 */
export function instanceOfItemApplicationListResponse(value: object): boolean {
    if (!('applications' in value)) return false;
    return true;
}

export function ItemApplicationListResponseFromJSON(json: any): ItemApplicationListResponse {
    return ItemApplicationListResponseFromJSONTyped(json, false);
}

export function ItemApplicationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemApplicationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'request_id': json['request_id'] == null ? undefined : json['request_id'],
        'applications': ((json['applications'] as Array<any>).map(ConnectedApplicationFromJSON)),
    };
}

export function ItemApplicationListResponseToJSON(value?: ItemApplicationListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'request_id': value['request_id'],
        'applications': ((value['applications'] as Array<any>).map(ConnectedApplicationToJSON)),
    };
}

