/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiabilitiesGetRequestOptions } from './LiabilitiesGetRequestOptions';
import {
    LiabilitiesGetRequestOptionsFromJSON,
    LiabilitiesGetRequestOptionsFromJSONTyped,
    LiabilitiesGetRequestOptionsToJSON,
} from './LiabilitiesGetRequestOptions';

/**
 * LiabilitiesGetRequest defines the request schema for `/liabilities/get`
 * @export
 * @interface LiabilitiesGetRequest
 */
export interface LiabilitiesGetRequest {
    /**
     * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
     * @type {string}
     * @memberof LiabilitiesGetRequest
     */
    client_id?: string;
    /**
     * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
     * @type {string}
     * @memberof LiabilitiesGetRequest
     */
    secret?: string;
    /**
     * The access token associated with the Item data is being requested for.
     * @type {string}
     * @memberof LiabilitiesGetRequest
     */
    access_token: string;
    /**
     * 
     * @type {LiabilitiesGetRequestOptions}
     * @memberof LiabilitiesGetRequest
     */
    options?: LiabilitiesGetRequestOptions;
}

/**
 * Check if a given object implements the LiabilitiesGetRequest interface.
 */
export function instanceOfLiabilitiesGetRequest(value: object): boolean {
    if (!('access_token' in value)) return false;
    return true;
}

export function LiabilitiesGetRequestFromJSON(json: any): LiabilitiesGetRequest {
    return LiabilitiesGetRequestFromJSONTyped(json, false);
}

export function LiabilitiesGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiabilitiesGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'access_token': json['access_token'],
        'options': json['options'] == null ? undefined : LiabilitiesGetRequestOptionsFromJSON(json['options']),
    };
}

export function LiabilitiesGetRequestToJSON(value?: LiabilitiesGetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_id': value['client_id'],
        'secret': value['secret'],
        'access_token': value['access_token'],
        'options': LiabilitiesGetRequestOptionsToJSON(value['options']),
    };
}

