/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkDeliverySessionStatus } from './LinkDeliverySessionStatus';
import {
    LinkDeliverySessionStatusFromJSON,
    LinkDeliverySessionStatusFromJSONTyped,
    LinkDeliverySessionStatusToJSON,
} from './LinkDeliverySessionStatus';

/**
 * LinkDeliveryGetRequest defines the response schema for `/link_delivery/get`
 * @export
 * @interface LinkDeliveryGetResponse
 */
export interface LinkDeliveryGetResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {LinkDeliverySessionStatus}
     * @memberof LinkDeliveryGetResponse
     */
    status: LinkDeliverySessionStatus;
    /**
     * Timestamp in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:mm:ssZ`) indicating the time the given Hosted Link session was created at.
     * @type {Date}
     * @memberof LinkDeliveryGetResponse
     */
    created_at: Date;
    /**
     * Timestamp in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:mm:ssZ`) indicating the time the given Hosted Link session was completed at.
     * @type {Date}
     * @memberof LinkDeliveryGetResponse
     */
    completed_at?: Date;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof LinkDeliveryGetResponse
     */
    request_id: string;
    /**
     * An array of access tokens associated with the Hosted Link session.
     * @type {Array<string>}
     * @memberof LinkDeliveryGetResponse
     */
    access_tokens?: Array<string>;
    /**
     * An array of `item_id`s associated with the Hosted Link session.
     * @type {Array<string>}
     * @memberof LinkDeliveryGetResponse
     */
    item_ids?: Array<string>;
}

/**
 * Check if a given object implements the LinkDeliveryGetResponse interface.
 */
export function instanceOfLinkDeliveryGetResponse(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('created_at' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function LinkDeliveryGetResponseFromJSON(json: any): LinkDeliveryGetResponse {
    return LinkDeliveryGetResponseFromJSONTyped(json, false);
}

export function LinkDeliveryGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDeliveryGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': LinkDeliverySessionStatusFromJSON(json['status']),
        'created_at': (new Date(json['created_at'])),
        'completed_at': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'request_id': json['request_id'],
        'access_tokens': json['access_tokens'] == null ? undefined : json['access_tokens'],
        'item_ids': json['item_ids'] == null ? undefined : json['item_ids'],
    };
}

export function LinkDeliveryGetResponseToJSON(value?: LinkDeliveryGetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'status': LinkDeliverySessionStatusToJSON(value['status']),
        'created_at': ((value['created_at']).toISOString()),
        'completed_at': value['completed_at'] == null ? undefined : ((value['completed_at'] as any).toISOString()),
        'request_id': value['request_id'],
        'access_tokens': value['access_tokens'],
        'item_ids': value['item_ids'],
    };
}

