/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrismProduct } from './PrismProduct';
import {
    PrismProductFromJSON,
    PrismProductFromJSONTyped,
    PrismProductToJSON,
} from './PrismProduct';

/**
 * Specifies options for initializing Link for use with the Credit Partner Insights product.
 * @export
 * @interface LinkTokenCreateRequestCreditPartnerInsights
 */
export interface LinkTokenCreateRequestCreditPartnerInsights {
    /**
     * The maximum integer number of days of history to compute Crdit Partner Insights. Defaults to 180 if not specified
     * @type {number}
     * @memberof LinkTokenCreateRequestCreditPartnerInsights
     */
    days_requested?: number;
    /**
     * The specific prism products to return. If none are passed in, then all products will be returned.
     * @type {Array<PrismProduct>}
     * @memberof LinkTokenCreateRequestCreditPartnerInsights
     */
    prism_products?: Array<PrismProduct>;
}

/**
 * Check if a given object implements the LinkTokenCreateRequestCreditPartnerInsights interface.
 */
export function instanceOfLinkTokenCreateRequestCreditPartnerInsights(value: object): boolean {
    return true;
}

export function LinkTokenCreateRequestCreditPartnerInsightsFromJSON(json: any): LinkTokenCreateRequestCreditPartnerInsights {
    return LinkTokenCreateRequestCreditPartnerInsightsFromJSONTyped(json, false);
}

export function LinkTokenCreateRequestCreditPartnerInsightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTokenCreateRequestCreditPartnerInsights {
    if (json == null) {
        return json;
    }
    return {
        
        'days_requested': json['days_requested'] == null ? undefined : json['days_requested'],
        'prism_products': json['prism_products'] == null ? undefined : ((json['prism_products'] as Array<any>).map(PrismProductFromJSON)),
    };
}

export function LinkTokenCreateRequestCreditPartnerInsightsToJSON(value?: LinkTokenCreateRequestCreditPartnerInsights | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'days_requested': value['days_requested'],
        'prism_products': value['prism_products'] == null ? undefined : ((value['prism_products'] as Array<any>).map(PrismProductToJSON)),
    };
}

