/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkDeliveryWebhookCommunicationMethod } from './LinkDeliveryWebhookCommunicationMethod';
import {
    LinkDeliveryWebhookCommunicationMethodFromJSON,
    LinkDeliveryWebhookCommunicationMethodFromJSONTyped,
    LinkDeliveryWebhookCommunicationMethodToJSON,
} from './LinkDeliveryWebhookCommunicationMethod';
import type { LinkDeliveryWebhookDeliveryStatus } from './LinkDeliveryWebhookDeliveryStatus';
import {
    LinkDeliveryWebhookDeliveryStatusFromJSON,
    LinkDeliveryWebhookDeliveryStatusFromJSONTyped,
    LinkDeliveryWebhookDeliveryStatusToJSON,
} from './LinkDeliveryWebhookDeliveryStatus';

/**
 * Information related to the related to the delivery of the link session to users
 * @export
 * @interface LinkDeliveryMetadata
 */
export interface LinkDeliveryMetadata {
    [key: string]: any | any;
    /**
     * 
     * @type {LinkDeliveryWebhookCommunicationMethod}
     * @memberof LinkDeliveryMetadata
     */
    communication_method?: LinkDeliveryWebhookCommunicationMethod;
    /**
     * 
     * @type {LinkDeliveryWebhookDeliveryStatus}
     * @memberof LinkDeliveryMetadata
     */
    delivery_status?: LinkDeliveryWebhookDeliveryStatus;
}

/**
 * Check if a given object implements the LinkDeliveryMetadata interface.
 */
export function instanceOfLinkDeliveryMetadata(value: object): boolean {
    return true;
}

export function LinkDeliveryMetadataFromJSON(json: any): LinkDeliveryMetadata {
    return LinkDeliveryMetadataFromJSONTyped(json, false);
}

export function LinkDeliveryMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDeliveryMetadata {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'communication_method': json['communication_method'] == null ? undefined : LinkDeliveryWebhookCommunicationMethodFromJSON(json['communication_method']),
        'delivery_status': json['delivery_status'] == null ? undefined : LinkDeliveryWebhookDeliveryStatusFromJSON(json['delivery_status']),
    };
}

export function LinkDeliveryMetadataToJSON(value?: LinkDeliveryMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'communication_method': LinkDeliveryWebhookCommunicationMethodToJSON(value['communication_method']),
        'delivery_status': LinkDeliveryWebhookDeliveryStatusToJSON(value['delivery_status']),
    };
}

