/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The communication method used to deliver the Hosted Link session
 * @export
 */
export const LinkDeliveryWebhookCommunicationMethod = {
    Sms: 'SMS',
    Email: 'EMAIL'
} as const;
export type LinkDeliveryWebhookCommunicationMethod = typeof LinkDeliveryWebhookCommunicationMethod[keyof typeof LinkDeliveryWebhookCommunicationMethod];


export function LinkDeliveryWebhookCommunicationMethodFromJSON(json: any): LinkDeliveryWebhookCommunicationMethod {
    return LinkDeliveryWebhookCommunicationMethodFromJSONTyped(json, false);
}

export function LinkDeliveryWebhookCommunicationMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDeliveryWebhookCommunicationMethod {
    return json as LinkDeliveryWebhookCommunicationMethod;
}

export function LinkDeliveryWebhookCommunicationMethodToJSON(value?: LinkDeliveryWebhookCommunicationMethod | null): any {
    return value as any;
}

