/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A map containing data to pass in for the Card Switch flow.
 * @export
 * @interface LinkTokenCreateCardSwitch
 */
export interface LinkTokenCreateCardSwitch {
    /**
     * The BIN (Bank Identification Number) of the card to switch.
     * @type {string}
     * @memberof LinkTokenCreateCardSwitch
     */
    card_bin: string;
}

/**
 * Check if a given object implements the LinkTokenCreateCardSwitch interface.
 */
export function instanceOfLinkTokenCreateCardSwitch(value: object): boolean {
    if (!('card_bin' in value)) return false;
    return true;
}

export function LinkTokenCreateCardSwitchFromJSON(json: any): LinkTokenCreateCardSwitch {
    return LinkTokenCreateCardSwitchFromJSONTyped(json, false);
}

export function LinkTokenCreateCardSwitchFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTokenCreateCardSwitch {
    if (json == null) {
        return json;
    }
    return {
        
        'card_bin': json['card_bin'],
    };
}

export function LinkTokenCreateCardSwitchToJSON(value?: LinkTokenCreateCardSwitch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'card_bin': value['card_bin'],
    };
}

