/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Specifies options for initializing Link for use with Bank Employment. This field is required if `employment` is included in the `products` array and `bank` is specified in `employment_source_types`.
 * @export
 * @interface LinkTokenCreateRequestEmploymentBankIncome
 */
export interface LinkTokenCreateRequestEmploymentBankIncome {
    /**
     * The number of days of data to request for the Bank Employment product.
     * @type {number}
     * @memberof LinkTokenCreateRequestEmploymentBankIncome
     */
    days_requested: number;
}

/**
 * Check if a given object implements the LinkTokenCreateRequestEmploymentBankIncome interface.
 */
export function instanceOfLinkTokenCreateRequestEmploymentBankIncome(value: object): boolean {
    if (!('days_requested' in value)) return false;
    return true;
}

export function LinkTokenCreateRequestEmploymentBankIncomeFromJSON(json: any): LinkTokenCreateRequestEmploymentBankIncome {
    return LinkTokenCreateRequestEmploymentBankIncomeFromJSONTyped(json, false);
}

export function LinkTokenCreateRequestEmploymentBankIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTokenCreateRequestEmploymentBankIncome {
    if (json == null) {
        return json;
    }
    return {
        
        'days_requested': json['days_requested'],
    };
}

export function LinkTokenCreateRequestEmploymentBankIncomeToJSON(value?: LinkTokenCreateRequestEmploymentBankIncome | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'days_requested': value['days_requested'],
    };
}

