/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A value from a MISMO prescribed list that specifies the type of loan identifier.
 * @export
 */
export const LoanIdentifierType = {
    LenderLoan: 'LenderLoan',
    UniversalLoan: 'UniversalLoan'
} as const;
export type LoanIdentifierType = typeof LoanIdentifierType[keyof typeof LoanIdentifierType];


export function LoanIdentifierTypeFromJSON(json: any): LoanIdentifierType {
    return LoanIdentifierTypeFromJSONTyped(json, false);
}

export function LoanIdentifierTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanIdentifierType {
    return json as LoanIdentifierType;
}

export function LoanIdentifierTypeToJSON(value?: LoanIdentifierType | null): any {
    return value as any;
}

