/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoanIdentifiers } from './LoanIdentifiers';
import {
    LoanIdentifiersFromJSON,
    LoanIdentifiersFromJSONTyped,
    LoanIdentifiersToJSON,
} from './LoanIdentifiers';

/**
 * Information specific to a mortgage loan agreement between one or more borrowers and a mortgage lender.
 * @export
 * @interface Loan
 */
export interface Loan {
    [key: string]: any | any;
    /**
     * 
     * @type {LoanIdentifiers}
     * @memberof Loan
     */
    LOAN_IDENTIFIERS: LoanIdentifiers;
}

/**
 * Check if a given object implements the Loan interface.
 */
export function instanceOfLoan(value: object): boolean {
    if (!('LOAN_IDENTIFIERS' in value)) return false;
    return true;
}

export function LoanFromJSON(json: any): Loan {
    return LoanFromJSONTyped(json, false);
}

export function LoanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Loan {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'LOAN_IDENTIFIERS': LoanIdentifiersFromJSON(json['LOAN_IDENTIFIERS']),
    };
}

export function LoanToJSON(value?: Loan | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'LOAN_IDENTIFIERS': LoanIdentifiersToJSON(value['LOAN_IDENTIFIERS']),
    };
}

