/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Loan } from './Loan';
import {
    LoanFromJSON,
    LoanFromJSONTyped,
    LoanToJSON,
} from './Loan';

/**
 * A collection of loans that are part of a single deal.
 * @export
 * @interface Loans
 */
export interface Loans {
    [key: string]: any | any;
    /**
     * 
     * @type {Loan}
     * @memberof Loans
     */
    LOAN: Loan;
}

/**
 * Check if a given object implements the Loans interface.
 */
export function instanceOfLoans(value: object): boolean {
    if (!('LOAN' in value)) return false;
    return true;
}

export function LoansFromJSON(json: any): Loans {
    return LoansFromJSONTyped(json, false);
}

export function LoansFromJSONTyped(json: any, ignoreDiscriminator: boolean): Loans {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'LOAN': LoanFromJSON(json['LOAN']),
    };
}

export function LoansToJSON(value?: Loans | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'LOAN': LoanToJSON(value['LOAN']),
    };
}

