/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the given end customer.
 * 
 * `UNDER_REVIEW`: The end customer has been created and enabled in the non-Production environments. The end customer must be manually reviewed by the Plaid team before it can be enabled in production, at which point its status will automatically transition to `PENDING_ENABLEMENT` or `DENIED`.
 * 
 * `PENDING_ENABLEMENT`: The end customer is ready to be enabled in the Production environment. Call the `/partner/customer/enable` endpoint to enable the end customer in Production.
 * 
 * `ACTIVE`: The end customer has been enabled in all environments.
 * 
 * `DENIED`: The end customer has been created and enabled in the non-Production environments, but it did not pass review by the Plaid team and therefore cannot be enabled in the Production environment. Talk to your Account Manager for more information.
 * @export
 */
export const PartnerEndCustomerStatus = {
    UnderReview: 'UNDER_REVIEW',
    PendingEnablement: 'PENDING_ENABLEMENT',
    Active: 'ACTIVE',
    Denied: 'DENIED'
} as const;
export type PartnerEndCustomerStatus = typeof PartnerEndCustomerStatus[keyof typeof PartnerEndCustomerStatus];


export function PartnerEndCustomerStatusFromJSON(json: any): PartnerEndCustomerStatus {
    return PartnerEndCustomerStatusFromJSONTyped(json, false);
}

export function PartnerEndCustomerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerEndCustomerStatus {
    return json as PartnerEndCustomerStatus;
}

export function PartnerEndCustomerStatusToJSON(value?: PartnerEndCustomerStatus | null): any {
    return value as any;
}

