/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PaymentInitiationConsentRevokeResponse defines the response schema for `/payment_initation/consent/revoke`
 * @export
 * @interface PaymentInitiationConsentRevokeResponse
 */
export interface PaymentInitiationConsentRevokeResponse {
    [key: string]: any | any;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof PaymentInitiationConsentRevokeResponse
     */
    request_id?: string;
}

/**
 * Check if a given object implements the PaymentInitiationConsentRevokeResponse interface.
 */
export function instanceOfPaymentInitiationConsentRevokeResponse(value: object): boolean {
    return true;
}

export function PaymentInitiationConsentRevokeResponseFromJSON(json: any): PaymentInitiationConsentRevokeResponse {
    return PaymentInitiationConsentRevokeResponseFromJSONTyped(json, false);
}

export function PaymentInitiationConsentRevokeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInitiationConsentRevokeResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'request_id': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function PaymentInitiationConsentRevokeResponseToJSON(value?: PaymentInitiationConsentRevokeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'request_id': value['request_id'],
    };
}

