/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment scheme. If not specified - the default in the region will be used (e.g. `SEPA_CREDIT_TRANSFER` for EU). Using unsupported values will result in a failed payment.
 * 
 * `LOCAL_DEFAULT`: The default payment scheme for the selected market and currency will be used.
 * 
 * `LOCAL_INSTANT`: The instant payment scheme for the selected market and currency will be used (if applicable). Fees may be applied by the institution. If the market does not support an Instant Scheme (e.g. Denmark), the default in the region will be used.
 * 
 * `SEPA_CREDIT_TRANSFER`: The standard payment to a beneficiary within the SEPA area.
 * 
 * `SEPA_CREDIT_TRANSFER_INSTANT`: Instant payment within the SEPA area. May involve additional fees and may not be available at some banks.
 * @export
 */
export const PaymentScheme = {
    Null: 'null',
    LocalDefault: 'LOCAL_DEFAULT',
    LocalInstant: 'LOCAL_INSTANT',
    SepaCreditTransfer: 'SEPA_CREDIT_TRANSFER',
    SepaCreditTransferInstant: 'SEPA_CREDIT_TRANSFER_INSTANT'
} as const;
export type PaymentScheme = typeof PaymentScheme[keyof typeof PaymentScheme];


export function PaymentSchemeFromJSON(json: any): PaymentScheme {
    return PaymentSchemeFromJSONTyped(json, false);
}

export function PaymentSchemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentScheme {
    return json as PaymentScheme;
}

export function PaymentSchemeToJSON(value?: PaymentScheme | null): any {
    return value as any;
}

