/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Transaction information specific to inter-bank transfers. If the transaction was not an inter-bank transfer, all fields will be `null`.
 * 
 * If the `transactions` object was returned by a Transactions endpoint such as `/transactions/sync` or `/transactions/get`, the `payment_meta` key will always appear, but no data elements are guaranteed. If the `transactions` object was returned by an Assets endpoint such as `/asset_report/get/` or `/asset_report/pdf/get`, this field will only appear in an Asset Report with Insights.
 * @export
 * @interface PaymentMeta
 */
export interface PaymentMeta {
    [key: string]: any | any;
    /**
     * The transaction reference number supplied by the financial institution.
     * @type {string}
     * @memberof PaymentMeta
     */
    reference_number: string | null;
    /**
     * The ACH PPD ID for the payer.
     * @type {string}
     * @memberof PaymentMeta
     */
    ppd_id: string | null;
    /**
     * For transfers, the party that is receiving the transaction.
     * @type {string}
     * @memberof PaymentMeta
     */
    payee: string | null;
    /**
     * The party initiating a wire transfer. Will be `null` if the transaction is not a wire transfer.
     * @type {string}
     * @memberof PaymentMeta
     */
    by_order_of: string | null;
    /**
     * For transfers, the party that is paying the transaction.
     * @type {string}
     * @memberof PaymentMeta
     */
    payer: string | null;
    /**
     * The type of transfer, e.g. 'ACH'
     * @type {string}
     * @memberof PaymentMeta
     */
    payment_method: string | null;
    /**
     * The name of the payment processor
     * @type {string}
     * @memberof PaymentMeta
     */
    payment_processor: string | null;
    /**
     * The payer-supplied description of the transfer.
     * @type {string}
     * @memberof PaymentMeta
     */
    reason: string | null;
}

/**
 * Check if a given object implements the PaymentMeta interface.
 */
export function instanceOfPaymentMeta(value: object): boolean {
    if (!('reference_number' in value)) return false;
    if (!('ppd_id' in value)) return false;
    if (!('payee' in value)) return false;
    if (!('by_order_of' in value)) return false;
    if (!('payer' in value)) return false;
    if (!('payment_method' in value)) return false;
    if (!('payment_processor' in value)) return false;
    if (!('reason' in value)) return false;
    return true;
}

export function PaymentMetaFromJSON(json: any): PaymentMeta {
    return PaymentMetaFromJSONTyped(json, false);
}

export function PaymentMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMeta {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'reference_number': json['reference_number'],
        'ppd_id': json['ppd_id'],
        'payee': json['payee'],
        'by_order_of': json['by_order_of'],
        'payer': json['payer'],
        'payment_method': json['payment_method'],
        'payment_processor': json['payment_processor'],
        'reason': json['reason'],
    };
}

export function PaymentMetaToJSON(value?: PaymentMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'reference_number': value['reference_number'],
        'ppd_id': value['ppd_id'],
        'payee': value['payee'],
        'by_order_of': value['by_order_of'],
        'payer': value['payer'],
        'payment_method': value['payment_method'],
        'payment_processor': value['payment_processor'],
        'reason': value['reason'],
    };
}

