/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentRiskSignalsObject } from './DocumentRiskSignalsObject';
import {
    DocumentRiskSignalsObjectFromJSON,
    DocumentRiskSignalsObjectFromJSONTyped,
    DocumentRiskSignalsObjectToJSON,
} from './DocumentRiskSignalsObject';

/**
 * Object containing fraud risk data pertaining to the Item linked as part of the verification.
 * @export
 * @interface PayrollRiskSignalsItem
 */
export interface PayrollRiskSignalsItem {
    [key: string]: any | any;
    /**
     * The `item_id` of the Item associated with this webhook, warning, or error
     * @type {string}
     * @memberof PayrollRiskSignalsItem
     */
    item_id: string;
    /**
     * Array of payroll income document authenticity data retrieved for each of the user's accounts.
     * @type {Array<DocumentRiskSignalsObject>}
     * @memberof PayrollRiskSignalsItem
     */
    verification_risk_signals: Array<DocumentRiskSignalsObject>;
}

/**
 * Check if a given object implements the PayrollRiskSignalsItem interface.
 */
export function instanceOfPayrollRiskSignalsItem(value: object): boolean {
    if (!('item_id' in value)) return false;
    if (!('verification_risk_signals' in value)) return false;
    return true;
}

export function PayrollRiskSignalsItemFromJSON(json: any): PayrollRiskSignalsItem {
    return PayrollRiskSignalsItemFromJSONTyped(json, false);
}

export function PayrollRiskSignalsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayrollRiskSignalsItem {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'item_id': json['item_id'],
        'verification_risk_signals': ((json['verification_risk_signals'] as Array<any>).map(DocumentRiskSignalsObjectFromJSON)),
    };
}

export function PayrollRiskSignalsItemToJSON(value?: PayrollRiskSignalsItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'item_id': value['item_id'],
        'verification_risk_signals': ((value['verification_risk_signals'] as Array<any>).map(DocumentRiskSignalsObjectToJSON)),
    };
}

