/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object representing both the current pay period and year to date amount for an earning category.
 * @export
 * @interface PayStubEarningsTotal
 */
export interface PayStubEarningsTotal {
    [key: string]: any | any;
    /**
     * Total amount of the earnings for this pay period.
     * @type {number}
     * @memberof PayStubEarningsTotal
     */
    current_amount: number | null;
    /**
     * Total number of hours worked for this pay period.
     * @type {number}
     * @memberof PayStubEarningsTotal
     */
    hours: number | null;
    /**
     * The ISO-4217 currency code of the line item. Always `null` if `unofficial_currency_code` is non-null.
     * @type {string}
     * @memberof PayStubEarningsTotal
     */
    iso_currency_code: string | null;
    /**
     * The unofficial currency code associated with the security. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
     * 
     * See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
     * @type {string}
     * @memberof PayStubEarningsTotal
     */
    unofficial_currency_code: string | null;
    /**
     * The total year-to-date amount of the earnings.
     * @type {number}
     * @memberof PayStubEarningsTotal
     */
    ytd_amount: number | null;
}

/**
 * Check if a given object implements the PayStubEarningsTotal interface.
 */
export function instanceOfPayStubEarningsTotal(value: object): boolean {
    if (!('current_amount' in value)) return false;
    if (!('hours' in value)) return false;
    if (!('iso_currency_code' in value)) return false;
    if (!('unofficial_currency_code' in value)) return false;
    if (!('ytd_amount' in value)) return false;
    return true;
}

export function PayStubEarningsTotalFromJSON(json: any): PayStubEarningsTotal {
    return PayStubEarningsTotalFromJSONTyped(json, false);
}

export function PayStubEarningsTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayStubEarningsTotal {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'current_amount': json['current_amount'],
        'hours': json['hours'],
        'iso_currency_code': json['iso_currency_code'],
        'unofficial_currency_code': json['unofficial_currency_code'],
        'ytd_amount': json['ytd_amount'],
    };
}

export function PayStubEarningsTotalToJSON(value?: PayStubEarningsTotal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'current_amount': value['current_amount'],
        'hours': value['hours'],
        'iso_currency_code': value['iso_currency_code'],
        'unofficial_currency_code': value['unofficial_currency_code'],
        'ytd_amount': value['ytd_amount'],
    };
}

