/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of identity document detected in the images provided. Will always be one of the following values:
 * 
 *   `drivers_license` - A driver's license issued by the associated country, establishing identity without any guarantee as to citizenship, and granting driving privileges
 * 
 *   `id_card` - A general national identification card, distinct from driver's licenses as it only establishes identity
 * 
 *   `passport` - A travel passport issued by the associated country for one of its citizens
 * 
 *   `residence_permit_card` - An identity document issued by the associated country permitting a foreign citizen to <em>temporarily</em> reside there
 * 
 *   `resident_card` - An identity document issued by the associated country permitting a foreign citizen to <em>permanently</em> reside there
 * 
 *   `visa` - An identity document issued by the associated country permitting a foreign citizen entry for a short duration and for a specific purpose, typically no longer than 6 months
 * 
 * Note: This value may be different from the ID type that the user selects within Link. For example, if they select "Driver's License" but then submit a picture of a passport, this field will say `passport`
 * @export
 */
export const PhysicalDocumentCategory = {
    DriversLicense: 'drivers_license',
    IdCard: 'id_card',
    Passport: 'passport',
    ResidencePermitCard: 'residence_permit_card',
    ResidentCard: 'resident_card',
    Visa: 'visa'
} as const;
export type PhysicalDocumentCategory = typeof PhysicalDocumentCategory[keyof typeof PhysicalDocumentCategory];


export function PhysicalDocumentCategoryFromJSON(json: any): PhysicalDocumentCategory {
    return PhysicalDocumentCategoryFromJSONTyped(json, false);
}

export function PhysicalDocumentCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicalDocumentCategory {
    return json as PhysicalDocumentCategory;
}

export function PhysicalDocumentCategoryToJSON(value?: PhysicalDocumentCategory | null): any {
    return value as any;
}

