/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A list of products that an institution can support. All Items must be initialized with at least one product. The Balance product is always available and does not need to be specified during initialization.
 * @export
 */
export const Products = {
    Assets: 'assets',
    Auth: 'auth',
    Balance: 'balance',
    Identity: 'identity',
    IdentityMatch: 'identity_match',
    Investments: 'investments',
    InvestmentsAuth: 'investments_auth',
    Liabilities: 'liabilities',
    PaymentInitiation: 'payment_initiation',
    IdentityVerification: 'identity_verification',
    Transactions: 'transactions',
    CreditDetails: 'credit_details',
    Income: 'income',
    IncomeVerification: 'income_verification',
    DepositSwitch: 'deposit_switch',
    StandingOrders: 'standing_orders',
    Transfer: 'transfer',
    Employment: 'employment',
    RecurringTransactions: 'recurring_transactions',
    Signal: 'signal',
    Statements: 'statements',
    ProcessorPayments: 'processor_payments',
    ProcessorIdentity: 'processor_identity'
} as const;
export type Products = typeof Products[keyof typeof Products];


export function ProductsFromJSON(json: any): Products {
    return ProductsFromJSONTyped(json, false);
}

export function ProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Products {
    return json as Products;
}

export function ProductsToJSON(value?: Products | null): any {
    return value as any;
}

