/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileIdentity } from './ProfileIdentity';
import {
    ProfileIdentityFromJSON,
    ProfileIdentityFromJSONTyped,
    ProfileIdentityToJSON,
} from './ProfileIdentity';
import type { ProfileItem } from './ProfileItem';
import {
    ProfileItemFromJSON,
    ProfileItemFromJSONTyped,
    ProfileItemToJSON,
} from './ProfileItem';

/**
 * ProfileGetResponse defines the response schema for `/profile/get`
 * @export
 * @interface ProfileGetResponse
 */
export interface ProfileGetResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {ProfileIdentity}
     * @memberof ProfileGetResponse
     */
    identity: ProfileIdentity | null;
    /**
     * 
     * @type {Array<ProfileItem>}
     * @memberof ProfileGetResponse
     */
    items: Array<ProfileItem>;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof ProfileGetResponse
     */
    request_id: string;
}

/**
 * Check if a given object implements the ProfileGetResponse interface.
 */
export function instanceOfProfileGetResponse(value: object): boolean {
    if (!('identity' in value)) return false;
    if (!('items' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function ProfileGetResponseFromJSON(json: any): ProfileGetResponse {
    return ProfileGetResponseFromJSONTyped(json, false);
}

export function ProfileGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'identity': ProfileIdentityFromJSON(json['identity']),
        'items': ((json['items'] as Array<any>).map(ProfileItemFromJSON)),
        'request_id': json['request_id'],
    };
}

export function ProfileGetResponseToJSON(value?: ProfileGetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'identity': ProfileIdentityToJSON(value['identity']),
        'items': ((value['items'] as Array<any>).map(ProfileItemToJSON)),
        'request_id': value['request_id'],
    };
}

