/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about the student's eligibility in the Public Service Loan Forgiveness program. This is only returned if the institution is FedLoan (`ins_116527`). 
 * @export
 * @interface PSLFStatus
 */
export interface PSLFStatus {
    [key: string]: any | any;
    /**
     * The estimated date borrower will have completed 120 qualifying monthly payments. Returned in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
     * @type {Date}
     * @memberof PSLFStatus
     */
    estimated_eligibility_date: Date | null;
    /**
     * The number of qualifying payments that have been made.
     * @type {number}
     * @memberof PSLFStatus
     */
    payments_made: number | null;
    /**
     * The number of qualifying payments remaining.
     * @type {number}
     * @memberof PSLFStatus
     */
    payments_remaining: number | null;
}

/**
 * Check if a given object implements the PSLFStatus interface.
 */
export function instanceOfPSLFStatus(value: object): boolean {
    if (!('estimated_eligibility_date' in value)) return false;
    if (!('payments_made' in value)) return false;
    if (!('payments_remaining' in value)) return false;
    return true;
}

export function PSLFStatusFromJSON(json: any): PSLFStatus {
    return PSLFStatusFromJSONTyped(json, false);
}

export function PSLFStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PSLFStatus {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'estimated_eligibility_date': (json['estimated_eligibility_date'] == null ? null : new Date(json['estimated_eligibility_date'])),
        'payments_made': json['payments_made'],
        'payments_remaining': json['payments_remaining'],
    };
}

export function PSLFStatusToJSON(value?: PSLFStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'estimated_eligibility_date': (value['estimated_eligibility_date'] == null ? null : (value['estimated_eligibility_date'] as any).toISOString().substring(0,10)),
        'payments_made': value['payments_made'],
        'payments_remaining': value['payments_remaining'],
    };
}

