/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object containing a BACS account number and sort code. If an IBAN is not provided or if you need to accept domestic GBP-denominated payments, BACS data is required.
 * @export
 * @interface RecipientBACS
 */
export interface RecipientBACS {
    [key: string]: any | any;
    /**
     * The account number of the account. Maximum of 10 characters.
     * @type {string}
     * @memberof RecipientBACS
     */
    account?: string;
    /**
     * The 6-character sort code of the account.
     * @type {string}
     * @memberof RecipientBACS
     */
    sort_code?: string;
}

/**
 * Check if a given object implements the RecipientBACS interface.
 */
export function instanceOfRecipientBACS(value: object): boolean {
    return true;
}

export function RecipientBACSFromJSON(json: any): RecipientBACS {
    return RecipientBACSFromJSONTyped(json, false);
}

export function RecipientBACSFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientBACS {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'account': json['account'] == null ? undefined : json['account'],
        'sort_code': json['sort_code'] == null ? undefined : json['sort_code'],
    };
}

export function RecipientBACSToJSON(value?: RecipientBACS | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'account': value['account'],
        'sort_code': value['sort_code'],
    };
}

