/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProxyType } from './ProxyType';
import {
    ProxyTypeFromJSON,
    ProxyTypeFromJSONTyped,
    ProxyTypeToJSON,
} from './ProxyType';

/**
 * Result summary object specifying values for `device` attributes of risk check.
 * @export
 * @interface RiskCheckDevice
 */
export interface RiskCheckDevice {
    [key: string]: any | any;
    /**
     * 
     * @type {ProxyType}
     * @memberof RiskCheckDevice
     */
    ip_proxy_type: ProxyType | null;
    /**
     * Count of spam lists the IP address is associated with if known.
     * @type {number}
     * @memberof RiskCheckDevice
     */
    ip_spam_list_count: number | null;
    /**
     * UTC offset of the timezone associated with the IP address.
     * @type {string}
     * @memberof RiskCheckDevice
     */
    ip_timezone_offset: string | null;
}

/**
 * Check if a given object implements the RiskCheckDevice interface.
 */
export function instanceOfRiskCheckDevice(value: object): boolean {
    if (!('ip_proxy_type' in value)) return false;
    if (!('ip_spam_list_count' in value)) return false;
    if (!('ip_timezone_offset' in value)) return false;
    return true;
}

export function RiskCheckDeviceFromJSON(json: any): RiskCheckDevice {
    return RiskCheckDeviceFromJSONTyped(json, false);
}

export function RiskCheckDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskCheckDevice {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'ip_proxy_type': ProxyTypeFromJSON(json['ip_proxy_type']),
        'ip_spam_list_count': json['ip_spam_list_count'],
        'ip_timezone_offset': json['ip_timezone_offset'],
    };
}

export function RiskCheckDeviceToJSON(value?: RiskCheckDevice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'ip_proxy_type': ProxyTypeToJSON(value['ip_proxy_type']),
        'ip_spam_list_count': value['ip_spam_list_count'],
        'ip_timezone_offset': value['ip_timezone_offset'],
    };
}

