/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details about the transaction result after evaluated by the requested risk profile. If a `risk_profile_key` is not provided, this field will be omitted. This feature is currently in closed beta; to request access, contact your account manager.
 * @export
 * @interface RiskProfile
 */
export interface RiskProfile {
    /**
     * The name of the risk profile used for this transaction.
     * @type {string}
     * @memberof RiskProfile
     */
    key?: string;
    /**
     * The name of the evaluated outcome for this transaction.
     * @type {string}
     * @memberof RiskProfile
     */
    outcome?: string;
}

/**
 * Check if a given object implements the RiskProfile interface.
 */
export function instanceOfRiskProfile(value: object): boolean {
    return true;
}

export function RiskProfileFromJSON(json: any): RiskProfile {
    return RiskProfileFromJSONTyped(json, false);
}

export function RiskProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
    };
}

export function RiskProfileToJSON(value?: RiskProfile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'outcome': value['outcome'],
    };
}

