/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SandboxPublicTokenCreateResponse defines the response schema for `/sandbox/public_token/create`
 * @export
 * @interface SandboxPublicTokenCreateResponse
 */
export interface SandboxPublicTokenCreateResponse {
    [key: string]: any | any;
    /**
     * A public token that can be exchanged for an access token using `/item/public_token/exchange`
     * @type {string}
     * @memberof SandboxPublicTokenCreateResponse
     */
    public_token: string;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof SandboxPublicTokenCreateResponse
     */
    request_id: string;
}

/**
 * Check if a given object implements the SandboxPublicTokenCreateResponse interface.
 */
export function instanceOfSandboxPublicTokenCreateResponse(value: object): boolean {
    if (!('public_token' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function SandboxPublicTokenCreateResponseFromJSON(json: any): SandboxPublicTokenCreateResponse {
    return SandboxPublicTokenCreateResponseFromJSONTyped(json, false);
}

export function SandboxPublicTokenCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxPublicTokenCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'public_token': json['public_token'],
        'request_id': json['request_id'],
    };
}

export function SandboxPublicTokenCreateResponseToJSON(value?: SandboxPublicTokenCreateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'public_token': value['public_token'],
        'request_id': value['request_id'],
    };
}

