/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchSummary } from './MatchSummary';
import {
    MatchSummaryFromJSON,
    MatchSummaryFromJSONTyped,
    MatchSummaryToJSON,
} from './MatchSummary';
import type { WatchlistScreeningDocument } from './WatchlistScreeningDocument';
import {
    WatchlistScreeningDocumentFromJSON,
    WatchlistScreeningDocumentFromJSONTyped,
    WatchlistScreeningDocumentToJSON,
} from './WatchlistScreeningDocument';

/**
 * Analyzed document information for the associated hit
 * @export
 * @interface ScreeningHitDocumentsItems
 */
export interface ScreeningHitDocumentsItems {
    [key: string]: any | any;
    /**
     * 
     * @type {MatchSummary}
     * @memberof ScreeningHitDocumentsItems
     */
    analysis?: MatchSummary;
    /**
     * 
     * @type {WatchlistScreeningDocument}
     * @memberof ScreeningHitDocumentsItems
     */
    data?: WatchlistScreeningDocument;
}

/**
 * Check if a given object implements the ScreeningHitDocumentsItems interface.
 */
export function instanceOfScreeningHitDocumentsItems(value: object): boolean {
    return true;
}

export function ScreeningHitDocumentsItemsFromJSON(json: any): ScreeningHitDocumentsItems {
    return ScreeningHitDocumentsItemsFromJSONTyped(json, false);
}

export function ScreeningHitDocumentsItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningHitDocumentsItems {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'analysis': json['analysis'] == null ? undefined : MatchSummaryFromJSON(json['analysis']),
        'data': json['data'] == null ? undefined : WatchlistScreeningDocumentFromJSON(json['data']),
    };
}

export function ScreeningHitDocumentsItemsToJSON(value?: ScreeningHitDocumentsItems | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'analysis': MatchSummaryToJSON(value['analysis']),
        'data': WatchlistScreeningDocumentToJSON(value['data']),
    };
}

