/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelfieCheckSelfie } from './SelfieCheckSelfie';
import {
    SelfieCheckSelfieFromJSON,
    SelfieCheckSelfieFromJSONTyped,
    SelfieCheckSelfieToJSON,
} from './SelfieCheckSelfie';
import type { SelfieCheckStatus } from './SelfieCheckStatus';
import {
    SelfieCheckStatusFromJSON,
    SelfieCheckStatusFromJSONTyped,
    SelfieCheckStatusToJSON,
} from './SelfieCheckStatus';

/**
 * Additional information for the `selfie_check` step. This field will be `null` unless `steps.selfie_check` has reached a terminal state of either `success` or `failed`.
 * @export
 * @interface SelfieCheck
 */
export interface SelfieCheck {
    [key: string]: any | any;
    /**
     * 
     * @type {SelfieCheckStatus}
     * @memberof SelfieCheck
     */
    status: SelfieCheckStatus;
    /**
     * An array of selfies submitted to the `selfie_check` step. Each entry represents one user submission.
     * @type {Array<SelfieCheckSelfie>}
     * @memberof SelfieCheck
     */
    selfies: Array<SelfieCheckSelfie>;
}

/**
 * Check if a given object implements the SelfieCheck interface.
 */
export function instanceOfSelfieCheck(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('selfies' in value)) return false;
    return true;
}

export function SelfieCheckFromJSON(json: any): SelfieCheck {
    return SelfieCheckFromJSONTyped(json, false);
}

export function SelfieCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelfieCheck {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': SelfieCheckStatusFromJSON(json['status']),
        'selfies': ((json['selfies'] as Array<any>).map(SelfieCheckSelfieFromJSON)),
    };
}

export function SelfieCheckToJSON(value?: SelfieCheck | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'status': SelfieCheckStatusToJSON(value['status']),
        'selfies': ((value['selfies'] as Array<any>).map(SelfieCheckSelfieToJSON)),
    };
}

