/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceProductFulfillmentIdentifier } from './ServiceProductFulfillmentIdentifier';
import {
    ServiceProductFulfillmentIdentifierFromJSON,
    ServiceProductFulfillmentIdentifierFromJSONTyped,
    ServiceProductFulfillmentIdentifierToJSON,
} from './ServiceProductFulfillmentIdentifier';

/**
 * Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
 * @export
 * @interface ServiceProductFulfillmentDetail
 */
export interface ServiceProductFulfillmentDetail {
    [key: string]: any | any;
    /**
     * A string that uniquely identifies a type of order Verification of Asset.
     * @type {string}
     * @memberof ServiceProductFulfillmentDetail
     */
    VendorOrderIdentifier: string | null;
    /**
     * 
     * @type {ServiceProductFulfillmentIdentifier}
     * @memberof ServiceProductFulfillmentDetail
     */
    ServiceProductFulfillmentIdentifier: ServiceProductFulfillmentIdentifier;
}

/**
 * Check if a given object implements the ServiceProductFulfillmentDetail interface.
 */
export function instanceOfServiceProductFulfillmentDetail(value: object): boolean {
    if (!('VendorOrderIdentifier' in value)) return false;
    if (!('ServiceProductFulfillmentIdentifier' in value)) return false;
    return true;
}

export function ServiceProductFulfillmentDetailFromJSON(json: any): ServiceProductFulfillmentDetail {
    return ServiceProductFulfillmentDetailFromJSONTyped(json, false);
}

export function ServiceProductFulfillmentDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceProductFulfillmentDetail {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'VendorOrderIdentifier': json['VendorOrderIdentifier'],
        'ServiceProductFulfillmentIdentifier': ServiceProductFulfillmentIdentifierFromJSON(json['ServiceProductFulfillmentIdentifier']),
    };
}

export function ServiceProductFulfillmentDetailToJSON(value?: ServiceProductFulfillmentDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'VendorOrderIdentifier': value['VendorOrderIdentifier'],
        'ServiceProductFulfillmentIdentifier': ServiceProductFulfillmentIdentifierToJSON(value['ServiceProductFulfillmentIdentifier']),
    };
}

