/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Conveys information about the errors causing missing or stale bank data used to construct the /signal/evaluate scores and response
 * @export
 * @interface SignalWarning
 */
export interface SignalWarning {
    /**
     * A broad categorization of the warning. Safe for programmatic use.
     * @type {string}
     * @memberof SignalWarning
     */
    warning_type?: string;
    /**
     * The warning code identifies a specific kind of warning that pertains to the error causing bank data to be missing. Safe for programmatic use. For more details on warning codes, please refer to Plaid standard error codes documentation. If you receive the `ITEM_LOGIN_REQUIRED` warning, we recommend re-authenticating your user by implementing Link's update mode. This will guide your user to fix their credentials, allowing Plaid to start fetching data again for future Signal requests.
     * @type {string}
     * @memberof SignalWarning
     */
    warning_code?: string;
    /**
     * A developer-friendly representation of the warning type. This may change over time and is not safe for programmatic use.
     * @type {string}
     * @memberof SignalWarning
     */
    warning_message?: string;
}

/**
 * Check if a given object implements the SignalWarning interface.
 */
export function instanceOfSignalWarning(value: object): boolean {
    return true;
}

export function SignalWarningFromJSON(json: any): SignalWarning {
    return SignalWarningFromJSONTyped(json, false);
}

export function SignalWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalWarning {
    if (json == null) {
        return json;
    }
    return {
        
        'warning_type': json['warning_type'] == null ? undefined : json['warning_type'],
        'warning_code': json['warning_code'] == null ? undefined : json['warning_code'],
        'warning_message': json['warning_message'] == null ? undefined : json['warning_message'],
    };
}

export function SignalWarningToJSON(value?: SignalWarning | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'warning_type': value['warning_type'],
        'warning_code': value['warning_code'],
        'warning_message': value['warning_message'],
    };
}

