/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The payment decision from the risk assessment.
 * 
 * `APPROVE`: approve the transaction without requiring further actions from your customers. For example, use this field if you are placing a standard hold for all the approved transactions before making funds available to your customers. You should also use this field if you decide to accelerate the fund availability for your customers.
 * 
 * `REVIEW`: the transaction requires manual review
 * 
 * `REJECT`: reject the transaction
 * 
 * `TAKE_OTHER_RISK_MEASURES`: for example, placing a longer hold on funds than those approved transactions or introducing customer frictions such as step-up verification/authentication
 * 
 * `NOT_EVALUATED`: if only logging the Signal results without using them
 * 
 * Possible values:  `APPROVE`, `REVIEW`, `REJECT`, `TAKE_OTHER_RISK_MEASURES`, `NOT_EVALUATED`
 * 
 * @export
 */
export const SignalDecisionOutcome = {
    Approve: 'APPROVE',
    Review: 'REVIEW',
    Reject: 'REJECT',
    TakeOtherRiskMeasures: 'TAKE_OTHER_RISK_MEASURES',
    NotEvaluated: 'NOT_EVALUATED'
} as const;
export type SignalDecisionOutcome = typeof SignalDecisionOutcome[keyof typeof SignalDecisionOutcome];


export function SignalDecisionOutcomeFromJSON(json: any): SignalDecisionOutcome {
    return SignalDecisionOutcomeFromJSONTyped(json, false);
}

export function SignalDecisionOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalDecisionOutcome {
    return json as SignalDecisionOutcome;
}

export function SignalDecisionOutcomeToJSON(value?: SignalDecisionOutcome | null): any {
    return value as any;
}

