/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferRefund } from './TransferRefund';
import {
    TransferRefundFromJSON,
    TransferRefundFromJSONTyped,
    TransferRefundToJSON,
} from './TransferRefund';

/**
 * Defines the response schema for `/transfer/refund/get`
 * @export
 * @interface TransferRefundGetResponse
 */
export interface TransferRefundGetResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {TransferRefund}
     * @memberof TransferRefundGetResponse
     */
    refund: TransferRefund;
    /**
     * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
     * @type {string}
     * @memberof TransferRefundGetResponse
     */
    request_id: string;
}

/**
 * Check if a given object implements the TransferRefundGetResponse interface.
 */
export function instanceOfTransferRefundGetResponse(value: object): boolean {
    if (!('refund' in value)) return false;
    if (!('request_id' in value)) return false;
    return true;
}

export function TransferRefundGetResponseFromJSON(json: any): TransferRefundGetResponse {
    return TransferRefundGetResponseFromJSONTyped(json, false);
}

export function TransferRefundGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRefundGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'refund': TransferRefundFromJSON(json['refund']),
        'request_id': json['request_id'],
    };
}

export function TransferRefundGetResponseToJSON(value?: TransferRefundGetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'refund': TransferRefundToJSON(value['refund']),
        'request_id': value['request_id'],
    };
}

