/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferAuthorizationGuaranteeDecisionRationaleCode } from './TransferAuthorizationGuaranteeDecisionRationaleCode';
import {
    TransferAuthorizationGuaranteeDecisionRationaleCodeFromJSON,
    TransferAuthorizationGuaranteeDecisionRationaleCodeFromJSONTyped,
    TransferAuthorizationGuaranteeDecisionRationaleCodeToJSON,
} from './TransferAuthorizationGuaranteeDecisionRationaleCode';

/**
 * The rationale for Plaid's decision to not guarantee a transfer. Will be `null` unless `guarantee_decision` is `NOT_GUARANTEED`.
 * @export
 * @interface TransferAuthorizationGuaranteeDecisionRationale
 */
export interface TransferAuthorizationGuaranteeDecisionRationale {
    [key: string]: any | any;
    /**
     * 
     * @type {TransferAuthorizationGuaranteeDecisionRationaleCode}
     * @memberof TransferAuthorizationGuaranteeDecisionRationale
     */
    code: TransferAuthorizationGuaranteeDecisionRationaleCode;
    /**
     * A human-readable description of why the transfer cannot be guaranteed.
     * @type {string}
     * @memberof TransferAuthorizationGuaranteeDecisionRationale
     */
    description: string;
}

/**
 * Check if a given object implements the TransferAuthorizationGuaranteeDecisionRationale interface.
 */
export function instanceOfTransferAuthorizationGuaranteeDecisionRationale(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('description' in value)) return false;
    return true;
}

export function TransferAuthorizationGuaranteeDecisionRationaleFromJSON(json: any): TransferAuthorizationGuaranteeDecisionRationale {
    return TransferAuthorizationGuaranteeDecisionRationaleFromJSONTyped(json, false);
}

export function TransferAuthorizationGuaranteeDecisionRationaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferAuthorizationGuaranteeDecisionRationale {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': TransferAuthorizationGuaranteeDecisionRationaleCodeFromJSON(json['code']),
        'description': json['description'],
    };
}

export function TransferAuthorizationGuaranteeDecisionRationaleToJSON(value?: TransferAuthorizationGuaranteeDecisionRationale | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'code': TransferAuthorizationGuaranteeDecisionRationaleCodeToJSON(value['code']),
        'description': value['description'],
    };
}

