/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The failure reason if the event type for a transfer is `"failed"` or `"returned"`. Null value otherwise.
 * @export
 * @interface TransferFailure
 */
export interface TransferFailure {
    [key: string]: any | any;
    /**
     * The ACH return code, e.g. `R01`.  A return code will be provided if and only if the transfer status is `returned`. For a full listing of ACH return codes, see [Transfer errors](https://plaid.com/docs/errors/transfer/#ach-return-codes).
     * @type {string}
     * @memberof TransferFailure
     */
    ach_return_code?: string;
    /**
     * A human-readable description of the reason for the failure or reversal.
     * @type {string}
     * @memberof TransferFailure
     */
    description?: string;
}

/**
 * Check if a given object implements the TransferFailure interface.
 */
export function instanceOfTransferFailure(value: object): boolean {
    return true;
}

export function TransferFailureFromJSON(json: any): TransferFailure {
    return TransferFailureFromJSONTyped(json, false);
}

export function TransferFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferFailure {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'ach_return_code': json['ach_return_code'] == null ? undefined : json['ach_return_code'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TransferFailureToJSON(value?: TransferFailure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'ach_return_code': value['ach_return_code'],
        'description': value['description'],
    };
}

