/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * TransactionsUserInsightsGetRequest defines the request schema for `/beta/transactions/user_insights/v1/get`.
 * @export
 * @interface TransactionsUserInsightsGetRequest
 */
export interface TransactionsUserInsightsGetRequest {
    /**
     * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
     * @type {string}
     * @memberof TransactionsUserInsightsGetRequest
     */
    client_id?: string;
    /**
     * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
     * @type {string}
     * @memberof TransactionsUserInsightsGetRequest
     */
    secret?: string;
    /**
     * A unique client-provided user_id to retrieve insights for.
     * @type {string}
     * @memberof TransactionsUserInsightsGetRequest
     */
    client_user_id: string;
}

/**
 * Check if a given object implements the TransactionsUserInsightsGetRequest interface.
 */
export function instanceOfTransactionsUserInsightsGetRequest(value: object): boolean {
    if (!('client_user_id' in value)) return false;
    return true;
}

export function TransactionsUserInsightsGetRequestFromJSON(json: any): TransactionsUserInsightsGetRequest {
    return TransactionsUserInsightsGetRequestFromJSONTyped(json, false);
}

export function TransactionsUserInsightsGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsUserInsightsGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'client_user_id': json['client_user_id'],
    };
}

export function TransactionsUserInsightsGetRequestToJSON(value?: TransactionsUserInsightsGetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_id': value['client_id'],
        'secret': value['secret'],
        'client_user_id': value['client_user_id'],
    };
}

