/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A code representing the rationale for approving or declining the proposed transfer.
 * 
 * If the `rationale_code` is `null`, the transfer passed the authorization check.
 * 
 * Any non-`null` value for an `approved` transfer indicates that the the authorization check could not be run and that you should perform your own risk assessment on the transfer. The code will indicate why the check could not be run. Possible values for an `approved` transfer are:
 * 
 * `MANUALLY_VERIFIED_ITEM` – Item created via same-day micro deposits, limited information available.
 * 
 * `ITEM_LOGIN_REQUIRED` – Unable to collect the account information due to Item staleness. Can be resolved by using Link in [update mode](https://www.plaid.com/docs/link/update-mode).
 * 
 * `MIGRATED_ACCOUNT_ITEM` - Item created via `/transfer/account_migration` endpoint, limited information available.
 * 
 * `ERROR` – Unable to collect the account information due to an unspecified error.
 * 
 * The following codes indicate that the authorization decision was `declined`:
 * 
 * `NSF` – Transaction likely to result in a return due to insufficient funds.
 * 
 * `RISK` - Transaction is high-risk.
 * 
 * `TRANSFER_LIMIT_REACHED` - One or several transfer limits are reached, e.g. monthly transfer limit.
 * @export
 */
export const TransferAuthorizationDecisionRationaleCode = {
    Nsf: 'NSF',
    Risk: 'RISK',
    TransferLimitReached: 'TRANSFER_LIMIT_REACHED',
    ManuallyVerifiedItem: 'MANUALLY_VERIFIED_ITEM',
    ItemLoginRequired: 'ITEM_LOGIN_REQUIRED',
    PaymentProfileLoginRequired: 'PAYMENT_PROFILE_LOGIN_REQUIRED',
    Error: 'ERROR',
    MigratedAccountItem: 'MIGRATED_ACCOUNT_ITEM',
    Null: 'null'
} as const;
export type TransferAuthorizationDecisionRationaleCode = typeof TransferAuthorizationDecisionRationaleCode[keyof typeof TransferAuthorizationDecisionRationaleCode];


export function TransferAuthorizationDecisionRationaleCodeFromJSON(json: any): TransferAuthorizationDecisionRationaleCode {
    return TransferAuthorizationDecisionRationaleCodeFromJSONTyped(json, false);
}

export function TransferAuthorizationDecisionRationaleCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferAuthorizationDecisionRationaleCode {
    return json as TransferAuthorizationDecisionRationaleCode;
}

export function TransferAuthorizationDecisionRationaleCodeToJSON(value?: TransferAuthorizationDecisionRationaleCode | null): any {
    return value as any;
}

