/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * W2 state and local wages
 * @export
 * @interface W2StateAndLocalWages
 */
export interface W2StateAndLocalWages {
    [key: string]: any | any;
    /**
     * State associated with the wage.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    state?: string;
    /**
     * State identification number of the employer.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    employer_state_id_number?: string;
    /**
     * Wages and tips from the specified state.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    state_wages_tips?: string;
    /**
     * Income tax from the specified state.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    state_income_tax?: string;
    /**
     * Wages and tips from the locality.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    local_wages_tips?: string;
    /**
     * Income tax from the locality.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    local_income_tax?: string;
    /**
     * Name of the locality.
     * @type {string}
     * @memberof W2StateAndLocalWages
     */
    locality_name?: string;
}

/**
 * Check if a given object implements the W2StateAndLocalWages interface.
 */
export function instanceOfW2StateAndLocalWages(value: object): boolean {
    return true;
}

export function W2StateAndLocalWagesFromJSON(json: any): W2StateAndLocalWages {
    return W2StateAndLocalWagesFromJSONTyped(json, false);
}

export function W2StateAndLocalWagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): W2StateAndLocalWages {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'state': json['state'] == null ? undefined : json['state'],
        'employer_state_id_number': json['employer_state_id_number'] == null ? undefined : json['employer_state_id_number'],
        'state_wages_tips': json['state_wages_tips'] == null ? undefined : json['state_wages_tips'],
        'state_income_tax': json['state_income_tax'] == null ? undefined : json['state_income_tax'],
        'local_wages_tips': json['local_wages_tips'] == null ? undefined : json['local_wages_tips'],
        'local_income_tax': json['local_income_tax'] == null ? undefined : json['local_income_tax'],
        'locality_name': json['locality_name'] == null ? undefined : json['locality_name'],
    };
}

export function W2StateAndLocalWagesToJSON(value?: W2StateAndLocalWages | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'state': value['state'],
        'employer_state_id_number': value['employer_state_id_number'],
        'state_wages_tips': value['state_wages_tips'],
        'state_income_tax': value['state_income_tax'],
        'local_wages_tips': value['local_wages_tips'],
        'local_income_tax': value['local_income_tax'],
        'locality_name': value['locality_name'],
    };
}

