/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the wallet.
 * 
 * `UNKNOWN`: The wallet status is unknown.
 * 
 * `ACTIVE`: The wallet is active and ready to send money to and receive money from.
 * 
 * `CLOSED`: The wallet is closed. Any transactions made to or from this wallet will error.
 * @export
 */
export const WalletStatus = {
    Unknown: 'UNKNOWN',
    Active: 'ACTIVE',
    Closed: 'CLOSED'
} as const;
export type WalletStatus = typeof WalletStatus[keyof typeof WalletStatus];


export function WalletStatusFromJSON(json: any): WalletStatus {
    return WalletStatusFromJSONTyped(json, false);
}

export function WalletStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletStatus {
    return json as WalletStatus;
}

export function WalletStatusToJSON(value?: WalletStatus | null): any {
    return value as any;
}

