/* tslint:disable */
/* eslint-disable */
/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the transaction.
 * 
 * `AUTHORISING`: The transaction is being processed for validation and compliance.
 * 
 * `INITIATED`: The transaction has been initiated and is currently being processed.
 * 
 * `EXECUTED`: The transaction has been successfully executed and is considered complete. This is only applicable for debit transactions.
 * 
 * `SETTLED`: The transaction has settled and funds are available for use. This is only applicable for credit transactions. A transaction will typically settle within seconds to several days, depending on which payment rail is used.
 * 
 * `FAILED`: The transaction failed to process successfully. This is a terminal status.
 * 
 * `BLOCKED`: The transaction has been blocked for violating compliance rules. This is a terminal status.
 * @export
 */
export const WalletTransactionStatus = {
    Authorising: 'AUTHORISING',
    Initiated: 'INITIATED',
    Executed: 'EXECUTED',
    Settled: 'SETTLED',
    Blocked: 'BLOCKED',
    Failed: 'FAILED'
} as const;
export type WalletTransactionStatus = typeof WalletTransactionStatus[keyof typeof WalletTransactionStatus];


export function WalletTransactionStatusFromJSON(json: any): WalletTransactionStatus {
    return WalletTransactionStatusFromJSONTyped(json, false);
}

export function WalletTransactionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletTransactionStatus {
    return json as WalletTransactionStatus;
}

export function WalletTransactionStatusToJSON(value?: WalletTransactionStatus | null): any {
    return value as any;
}

